-- =====================================================
-- MIGRATION: Add Primaria Desempeños - CYT 3°-6° and PS All Grades
-- This is a consolidated migration for efficiency
-- =====================================================

-- CYT 3° Primaria (11 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'CYT-C1-CAP1-D3P', 'Hace preguntas sobre hechos, fenómenos u objetos naturales y tecnológicos que explora. Elabora una posible explicación como respuesta, donde establece una relación entre los hechos y los factores que producen los cambios.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'CYT-C1-CAP2-D3P', 'Propone un plan donde describe las acciones y los procedimientos que utilizará para recoger información acerca de los factores relacionados con el problema en su indagación. Selecciona materiales, instrumentos y fuentes de información científica que le permiten comprobar la respuesta.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'CYT-C1-CAP3-D3P', 'Obtiene datos cualitativos o cuantitativos al llevar a cabo el plan que propuso para responder la pregunta. Usa unidades de medida convencionales y no convencionales, registra los datos y los representa en organizadores.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'CYT-C1-CAP4-D3P', 'Establece relaciones que expliquen el fenómeno estudiado. Utiliza los datos obtenidos y los compara con la respuesta que propuso, así como con información científica. Elabora sus conclusiones.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'CYT-C1-CAP5-D3P', 'Comunica las conclusiones de su indagación y lo que aprendió usando conocimientos científicos, así como el procedimiento, los logros y las dificultades que tuvo durante su desarrollo. Propone algunas mejoras. Da a conocer su indagación en forma oral o escrita.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'CYT-C2-CAP1-D3P', 'Describe los órganos que conforman los sistemas de plantas y animales. Ejemplo: El estudiante describe que la planta tiene raíz, tallo y hojas, y que los animales tienen sistemas digestivo, respiratorio y circulatorio.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'CYT-C2-CAP2-D3P', 'Compara las semejanzas y diferencias entre las características de los seres vivos y propone criterios para clasificarlos. Ejemplo: El estudiante compara los mamíferos con las aves y los clasifica según sus características.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'CYT-C3-CAP1-D3P', 'Determina el problema tecnológico, las causas que lo generan y su alternativa de solución, con base en conocimientos científicos o prácticas locales; asimismo, los requerimientos que debe cumplir y los recursos disponibles para construirla.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'CYT-C3-CAP2-D3P', 'Representa su alternativa de solución tecnológica con dibujos y textos; describe sus partes o etapas, la secuencia de pasos, características de forma, estructura y función. Selecciona herramientas, instrumentos y materiales según sus propiedades físicas.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'CYT-C3-CAP3-D3P', 'Construye su alternativa de solución tecnológica manipulando materiales, instrumentos y herramientas según sus funciones; cumple las normas de seguridad. Usa unidades de medida convencionales. Verifica el funcionamiento de su alternativa de solución tecnológica y realiza ajustes o cambios si es necesario para cumplir los requerimientos establecidos.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'CYT-C3-CAP4-D3P', 'Realiza pruebas para verificar si la solución tecnológica cumple con los requerimientos establecidos. Explica cómo construyó su solución tecnológica, su funcionamiento, el conocimiento científico o las prácticas locales aplicadas y las dificultades superadas.');

-- CYT 4° Primaria (11 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'CYT-C1-CAP1-D4P', 'Hace preguntas sobre hechos, fenómenos u objetos naturales y tecnológicos que explora y observa en su entorno. Propone posibles respuestas con base en el reconocimiento de regularidades identificadas en situaciones similares. Ejemplo: El estudiante podría preguntar: "¿Por qué una vela encendida se derrite y no ocurre lo mismo con un mechero?". Y podría responder: "La cera se consume más rápido que el gas del mechero".'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'CYT-C1-CAP2-D4P', 'Propone un plan donde describe las acciones y los procedimientos que utilizará para responder a la pregunta. Selecciona los materiales, instrumentos y fuentes de información científica que le permiten comprobar la respuesta.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'CYT-C1-CAP3-D4P', 'Obtiene datos cualitativos o cuantitativos al llevar a cabo el plan que propuso para responder la pregunta. Usa unidades de medida convencionales y no convencionales, registra los datos y los representa en organizadores gráficos o tablas.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'CYT-C1-CAP4-D4P', 'Establece relaciones que expliquen el fenómeno estudiado. Utiliza los datos cualitativos y cuantitativos que obtuvo y los compara con la respuesta que propuso, así como con la información científica que posee. Elabora sus conclusiones.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'CYT-C1-CAP5-D4P', 'Comunica las conclusiones de su indagación y lo que aprendió usando conocimientos científicos, así como el procedimiento, los logros y las dificultades que tuvo durante su desarrollo. Propone algunas mejoras. Da a conocer su indagación en forma oral o escrita.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'CYT-C2-CAP1-D4P', 'Describe las interacciones entre los seres vivos y los no vivos en su hábitat. Ejemplo: El estudiante describe cómo los herbívoros necesitan las plantas para alimentarse y cómo las plantas necesitan el suelo para crecer.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'CYT-C2-CAP2-D4P', 'Relaciona los cambios en el relieve de la Tierra con la acción del agua, el viento y el hielo. Ejemplo: El estudiante relaciona la erosión del suelo con el agua de lluvia o el viento.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'CYT-C3-CAP1-D4P', 'Determina el problema tecnológico y las causas que lo generan. Propone alternativas de solución con base en conocimientos científicos o prácticas locales, así como los requerimientos que debe cumplir y los recursos disponibles para construirlas.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'CYT-C3-CAP2-D4P', 'Representa su alternativa de solución tecnológica con dibujos y textos; describe sus partes, la secuencia de pasos para su implementación y selecciona herramientas, instrumentos y materiales según sus propiedades físicas.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'CYT-C3-CAP3-D4P', 'Construye su alternativa de solución tecnológica manipulando los materiales, instrumentos y herramientas según sus funciones; cumple las normas de seguridad y considera medidas de ecoeficiencia. Usa unidades de medida convencionales. Verifica el funcionamiento de su alternativa de solución tecnológica, detecta errores en la selección de materiales, imprecisiones en las dimensiones, procedimientos y realiza ajustes o cambios necesarios para cumplir los requerimientos establecidos.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'CYT-C3-CAP4-D4P', 'Realiza pruebas para verificar si la solución tecnológica cumple con los requerimientos establecidos. Explica cómo construyó su solución tecnológica, su funcionamiento, el conocimiento científico o las prácticas locales aplicadas, las dificultades superadas y los beneficios e inconvenientes de su uso.');

-- CYT 5° Primaria (11 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'CYT-C1-CAP1-D5P', 'Formula preguntas acerca de las variables que influyen en un hecho, fenómeno u objeto natural o tecnológico. Plantea hipótesis que expresan la relación causa-efecto y determina las variables involucradas.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'CYT-C1-CAP2-D5P', 'Propone un plan para observar las variables del problema de indagación y controlar aquellas que pueden modificar la experimentación, con la finalidad de obtener datos para comprobar sus hipótesis. Selecciona instrumentos, materiales y herramientas, así como fuentes que le brinden información científica. Considera el tiempo para el desarrollo del plan y las medidas de seguridad necesarias.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'CYT-C1-CAP3-D5P', 'Obtiene datos cualitativos o cuantitativos que evidencian la relación entre las variables que utiliza para responder la pregunta. Organiza los datos, hace cálculos de moda, proporcionalidad directa y otros, y los representa en diferentes organizadores.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'CYT-C1-CAP4-D5P', 'Utiliza los datos cualitativos o cuantitativos para probar sus hipótesis y las contrasta con información científica. Elabora sus conclusiones.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'CYT-C1-CAP5-D5P', 'Comunica sus conclusiones y lo que aprendió usando conocimientos científicos. Evalúa si los procedimientos seguidos en su indagación ayudaron a comprobar sus hipótesis. Menciona las dificultades que tuvo y propone mejoras. Da a conocer su indagación en forma oral o escrita.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'CYT-C2-CAP1-D5P', 'Describe las funciones de los sistemas de los seres vivos y cómo se relacionan entre sí. Ejemplo: El estudiante describe que el sistema digestivo transforma los alimentos en nutrientes que son transportados por el sistema circulatorio a todo el cuerpo.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'CYT-C2-CAP2-D5P', 'Justifica por qué los individuos se reproducen con otros de su misma especie. Ejemplo: El estudiante explica que las especies se reproducen entre sí para mantener sus características.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'CYT-C3-CAP1-D5P', 'Determina el problema tecnológico, las causas que lo generan y su alternativa de solución, con base en conocimientos científicos o prácticas locales; asimismo, determina los requerimientos que debe cumplir esa alternativa de solución y los recursos disponibles para construirla.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'CYT-C3-CAP2-D5P', 'Representa su alternativa de solución con dibujos estructurados. Describe sus partes o etapas, la secuencia de pasos, sus características de forma, estructura y función. Selecciona herramientas, instrumentos y materiales según sus propiedades físicas. Considera el presupuesto y el tiempo para desarrollarla.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'CYT-C3-CAP3-D5P', 'Construye su alternativa de solución tecnológica manipulando materiales, instrumentos y herramientas según su utilidad; cumple las normas de seguridad y considera medidas de ecoeficiencia. Usa unidades de medida convencionales. Verifica el funcionamiento de su alternativa de solución tecnológica, detecta imprecisiones y realiza ajustes para mejorarlo.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'CYT-C3-CAP4-D5P', 'Realiza pruebas para verificar si la solución tecnológica cumple con los requerimientos establecidos. Explica cómo construyó su solución tecnológica, su funcionamiento, el conocimiento científico o las prácticas locales aplicadas, las dificultades superadas y los beneficios e inconvenientes de su uso. Infiere impactos de la alternativa de solución tecnológica.');

-- CYT 6° Primaria (11 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'CYT-C1-CAP1-D6P', 'Formula preguntas acerca de las variables que influyen en un hecho, fenómeno u objeto natural o tecnológico. Plantea hipótesis que expresan la relación causa-efecto y determina las variables involucradas.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'CYT-C1-CAP2-D6P', 'Propone un plan para observar las variables del problema de indagación y controlar aquellas que pueden modificar la experimentación, con la finalidad de obtener datos para comprobar sus hipótesis. Selecciona instrumentos, materiales y herramientas, así como fuentes que le brinden información científica. Considera el tiempo para el desarrollo del plan y las medidas de seguridad necesarias.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'CYT-C1-CAP3-D6P', 'Obtiene datos cualitativos o cuantitativos que evidencian la relación entre las variables que utiliza para responder la pregunta. Registra los datos y los representa en diferentes organizadores.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'CYT-C1-CAP4-D6P', 'Utiliza los datos cualitativos o cuantitativos para probar sus hipótesis y las contrasta con información científica. Elabora sus conclusiones.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'CYT-C1-CAP5-D6P', 'Comunica sus conclusiones y lo que aprendió usando conocimientos científicos. Evalúa si los procedimientos seguidos en su indagación ayudaron a comprobar sus hipótesis. Menciona las dificultades que tuvo y propone mejoras. Da a conocer su indagación en forma oral o escrita.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'CYT-C2-CAP1-D6P', 'Explica con base en fuentes documentadas con respaldo científico, las relaciones que establece entre: las fuentes de energía o sus manifestaciones con los tipos de cambio que producen en los materiales; entre las fuerzas con el movimiento de los cuerpos; la estructura de los sistemas vivos con sus funciones y su agrupación en especies; la radiación del sol con las zonas climáticas de la Tierra y las adaptaciones de los seres vivos. Opina sobre los impactos de diversas tecnologías en la solución de problemas relacionados a necesidades y estilos de vida colectivas.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'CYT-C2-CAP2-D6P', 'Argumenta por qué la creación de objetos tecnológicos para satisfacer necesidades requiere de personas que tienen diferentes ocupaciones o especialidades, y opina sobre cómo el uso de los objetos tecnológicos impacta en el ambiente.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'CYT-C3-CAP1-D6P', 'Determina el problema tecnológico, las causas que lo generan y su alternativa de solución, con base en conocimientos científicos o prácticas locales; asimismo, determina los requerimientos que debe cumplir esa alternativa de solución, los recursos disponibles para construirla, y sus beneficios directos e indirectos.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'CYT-C3-CAP2-D6P', 'Representa su alternativa de solución con dibujos estructurados a escala. Describe sus partes o etapas, la secuencia de pasos, sus características de forma, estructura, función y explica el procedimiento, los recursos para implementarla, así como las herramientas y materiales seleccionados; verifica el alcance de su funcionamiento para el cumplimiento de los requerimientos. Calcula y estima el presupuesto y el tiempo necesario.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'CYT-C3-CAP3-D6P', 'Construye su alternativa de solución tecnológica manipulando materiales, instrumentos y herramientas según su utilidad; cumple las normas de seguridad y considera medidas de ecoeficiencia. Usa unidades de medida convencionales. Verifica el funcionamiento de su alternativa de solución tecnológica, detecta imprecisiones y realiza ajustes para mejorarlo.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'CYT-C3-CAP4-D6P', 'Realiza pruebas para verificar si la solución tecnológica cumple con los requerimientos establecidos. Explica cómo construyó su solución tecnológica, su funcionamiento, el conocimiento científico o las prácticas locales aplicadas, las dificultades superadas y los beneficios e inconvenientes de su uso. Infiere impactos de la alternativa de solución tecnológica y propone estrategias para reducir los posibles efectos negativos.');
