-- Migration: Add Estándares y Desempeños Precisados for DPCC (Ciclo VI and VII)
-- Date: 2026-03-13

-- ============================================================================
-- ESTÁNDARES DE APRENDIZAJE
-- ============================================================================

INSERT INTO estandares (competencia_id, ciclo, descripcion) VALUES
-- DPCC-C1 (Construye su identidad)
((SELECT id FROM competencias WHERE codigo = 'DPCC-C1' LIMIT 1), 'VI', 'Construye su identidad al tomar conciencia de los aspectos que lo hacen único, cuando se reconoce a sí mismo a partir de sus características personales, culturales y sociales, y de sus logros, valorando el aporte de las familias en su formación personal. Se desenvuelve con agrado y confianza en diversos grupos. Selecciona y utiliza las estrategias más adecuadas para regular sus emociones y comportamiento, y comprende las razones de los comportamientos propios y de los otros. Argumenta su posición frente a situaciones de conflicto moral, considerando las intenciones de las personas involucradas, los principios éticos y las normas establecidas. Analiza las consecuencias de sus decisiones y se propone comportamientos en los que estén presentes criterios éticos.'),
((SELECT id FROM competencias WHERE codigo = 'DPCC-C1' LIMIT 1), 'VII', 'Construye su identidad al tomar conciencia de los aspectos que lo hacen único, cuando se reconoce a sí mismo y valora sus identidades, sus logros y los cambios que se dan en su desarrollo. Se reconoce como parte de un mundo globalizado. Manifiesta de manera regulada sus emociones, sentimientos, logros e ideas distinguiendo el contexto y las personas, y comprendiendo sus causas y consecuencias. Asume una postura ética frente a una situación de conflicto moral, integrando en su argumentación principios éticos, los derechos fundamentales, la dignidad de todas las personas. Reflexiona sobre las consecuencias de sus decisiones. Se plantea comportamientos que incluyen elementos éticos de respeto a los derechos de los demás y de búsqueda de justicia teniendo en cuenta la responsabilidad de cada quien por sus acciones. Se relaciona con los demás bajo un marco de derechos, sin discriminar por género u orientación sexual y sin violencia. Desarrolla relaciones afectivas, de amistad o de pareja, basadas en la reciprocidad y el respeto. Identifica situaciones que vulneran los derechos sexuales y reproductivos y propone pautas para prevenirlas y protegerse frente a ellas.'),

-- DPCC-C2 (Convive y participa democráticamente en la búsqueda del bien común)
((SELECT id FROM competencias WHERE codigo = 'DPCC-C2' LIMIT 1), 'VI', 'Convive y participa democráticamente cuando se relaciona con los demás, respetando las diferencias y los derechos de cada uno, cumpliendo sus deberes y buscando que otros también las cumplan. Se relaciona con personas de cultures distintas, respetando sus costumbres. Construye y evalúa de manera colectiva las normas de convivencia en el aula y en la escuela con base en principios democráticos. Ejerce el rol de mediador en su grupo haciendo uso de la negociación y el diálogo para el manejo de conflictos. Propone, planifica y ejecuta acciones de manera cooperativa, dirigidas a promover el bien común, la defensa de sus derechos y el cumplimiento de sus deberes como miembro de una comunidad. Delibera sobre asuntos públicos formulando preguntas sobre sus causas y consecuencias, analizando argumentos contrarios a los propios y argumentando su postura basándose en fuentes y en otras opiniones.'),
((SELECT id FROM competencias WHERE codigo = 'DPCC-C2' LIMIT 1), 'VII', 'Convive y participa democráticamente, relacionándose con los demás, respetando las diferencias y promoviendo los derechos de todos, así como cumpliendo sus deberes y evaluando sus consecuencias. Se relaciona con personas de diferentes culturas respetando sus costumbres y creencias. Evalúa y propone normas para la convivencia social basadas en los principios democráticos y en la legislación vigente. Utiliza estrategias de negociación y diálogo para el manejo de conflictos. Asume deberes en la organización y ejecución de acciones colectivas para promover sus derechos y deberes frente a situaciones que involucran a su comunidad. Delibera sobre asuntos públicos con argumentos basados en fuentes confiables, los principios democráticos y la institucionalidad, y aporta a la construcción de consensos. Rechaza posiciones que legitiman la violencia o la vulneración de derechos.')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- DESEMPEÑOS PRECISADOS - DPCC-C1 & DPCC-C2 (Ciclos VI - VII)
-- ============================================================================

INSERT INTO desempenos_precisados (desempeno_id, descripcion) VALUES

-- -------------------------------------------------------------
-- 1ro Secundaria - DPCC-C1
-- -------------------------------------------------------------
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP1' AND g.nombre = '1° Secundaria' LIMIT 1), 'Explica los cambios propios de su etapa de desarrollo valorando sus características personales y culturales, y reconociendo la importancia de evitar y prevenir situaciones de riesgo (adicciones, delincuencia, pandillaje, desórdenes alimenticios, entre otros).'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP1' AND g.nombre = '1° Secundaria' LIMIT 1), 'Describe las principales prácticas culturales de los diversos grupos culturales y sociales a los que pertenece y explica cómo estas prácticas culturales lo ayudan a enriquecer su identidad personal.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP2' AND g.nombre = '1° Secundaria' LIMIT 1), 'Describe las causas y consecuencias de sus emociones, sentimientos y comportamientos, y las de sus compañeros en situaciones de convivencia en la escuela. Utiliza estrategias de autorregulación emocional de acuerdo con la situación que se presenta.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP3' AND g.nombre = '1° Secundaria' LIMIT 1), 'Argumenta su posición sobre dilemas morales que involucran situaciones de convivencia en su familia y en el aula tomando en cuenta las normas y las intenciones de las personas.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP3' AND g.nombre = '1° Secundaria' LIMIT 1), 'Explica las consecuencias de sus decisiones y propone acciones a partir de principios éticos.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP4' AND g.nombre = '1° Secundaria' LIMIT 1), 'Se relaciona con sus compañeros y compañeras con equidad, reflexiona sobre los efectos de las normas sociales en la vida de mujeres y varones, y muestra rechazo frente a aquellas que generan desigualdad. Expresa argumentos a favor del respeto y cuidado mutuo en las relaciones de amistad y enamoramiento.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP4' AND g.nombre = '1° Secundaria' LIMIT 1), 'Dialoga sobre la importancia del cuidado de sí mismo en relación con la salud sexual y reproductiva, e identifica situaciones que la ponen en riesgo.'),

-- -------------------------------------------------------------
-- 2do Secundaria - DPCC-C1
-- -------------------------------------------------------------
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP1' AND g.nombre = '2° Secundaria' LIMIT 1), 'Explica sus características personales, culturales y sociales, y sus logros. Valora la participación de su familia en su formación y reconoce la importancia de usar estrategias de protección frente a situaciones de riesgo.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP1' AND g.nombre = '2° Secundaria' LIMIT 1), 'Explica la importancia de participar, con seguridad y confianza, en diferentes grupos culturales y sociales (religiosos, ambientales, animalistas, de género, organizaciones juveniles, etc.) para enriquecer su identidad y sentirse parte de su comunidad.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP2' AND g.nombre = '2° Secundaria' LIMIT 1), 'Explica las causas y consecuencias de sus emociones, sentimientos y comportamientos, y las de los demás en diversas situaciones. Utiliza estrategias de autorregulación emocional de acuerdo con la situación que se presenta, y explica la importancia de expresar y autorregular sus emociones.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP3' AND g.nombre = '2° Secundaria' LIMIT 1), 'Argumenta su posición sobre dilemas morales que involucran situaciones de convivencia en la escuela y la comunidad tomando en cuenta las intenciones de las personas involucradas, los principios éticos y las normas establecidas.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP3' AND g.nombre = '2° Secundaria' LIMIT 1), 'Explica las consecuencias de sus decisiones y propone acciones en las que estén presentes criterios éticos para mejorar su comportamiento.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP4' AND g.nombre = '2° Secundaria' LIMIT 1), 'Se relaciona con sus compañeros y compañeras con equidad o igualdad, y analiza críticamente situaciones de desigualdad de género y violencia familiar, sexual y contra la mujer. Promueve el cuidado del otro y la reciprocidad en las relaciones de amistad y pareja.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP4' AND g.nombre = '2° Secundaria' LIMIT 1), 'Plantea pautas de prevención y protección ante situaciones que afecten su integridad sexual y reproductiva reconociendo la importancia del autocuidado.'),

-- -------------------------------------------------------------
-- 3ro Secundaria - DPCC-C1
-- -------------------------------------------------------------
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP1' AND g.nombre = '3° Secundaria' LIMIT 1), 'Explica y valora sus características personales, culturales y sociales, y sus logros y sus potencialidades. Explica que cada persona tiene un proceso propio de desarrollo y reconoce sus habilidades para superar la adversidad y afrontar situaciones de riesgo y oportunidad.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP1' AND g.nombre = '3° Secundaria' LIMIT 1), 'Opina reflexivamente sobre las prácticas culturales de su pueblo, y muestra aprecio por su herencia cultural y natural y la del país sintiéndose parte de él.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP2' AND g.nombre = '3° Secundaria' LIMIT 1), 'Expresa sus emociones, sentimientos y comportamiento de acuerdo con la situación que se presenta. Explica sus causas y consecuencias, y utiliza estrategias de autorregulación que le permiten establecer relaciones asertivas.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP3' AND g.nombre = '3° Secundaria' LIMIT 1), 'Sustenta, con argumentos razonados, una posición ética ante una situación de conflicto moral que involucra los derechos humanos.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP3' AND g.nombre = '3° Secundaria' LIMIT 1), 'Expresa opiniones sobre las consecuencias de sus decisiones y propone acciones basadas en principios éticos y en los derechos humanos.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP4' AND g.nombre = '3° Secundaria' LIMIT 1), 'Se relaciona con mujeres y varones con equidad. Analiza críticamente los estereotipos relacionados con la sexualidad y aquellos que son fuente de discriminación. Reconoce conductas violentas en las relaciones familiares de amistad o pareja, y muestra rechazo frente a ellas. Explica la importancia del respeto, el consentimiento, el cuidado del otro y la reciprocidad.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP4' AND g.nombre = '3° Secundaria' LIMIT 1), 'Propone pautas para prevenir y protegerse de situaciones que vulneran sus derechos sexuales y reproductivos considerando la dignidad de las personas.'),

-- -------------------------------------------------------------
-- 4to Secundaria - DPCC-C1
-- -------------------------------------------------------------
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP1' AND g.nombre = '4° Secundaria' LIMIT 1), 'Explica las características personales, culturales y sociales que lo hacen único. Describe sus potencialidades y limitaciones, y muestra disposición para utilizarlas en situaciones de riesgo.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP1' AND g.nombre = '4° Secundaria' LIMIT 1), 'Opina reflexivamente sobre las prácticas culturales de su país y se identifica con ellas. Explica la importancia de identificarse con los grupos sociales (familia, escuela, asociaciones religiosas, ambientales, ecologistas, etc.) que configuran su identidad y que contribuyen a su desarrollo y al de los demás.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP2' AND g.nombre = '4° Secundaria' LIMIT 1), 'Expresa sus emociones, sentimientos y comportamientos, y analiza sus causas y consecuencias. Utiliza estrategias de autorregulación que le permiten establecer relaciones empáticas.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP3' AND g.nombre = '4° Secundaria' LIMIT 1), 'Sustenta, con argumentos razonados, una posición ética ante una situación de conflicto moral considerando principios éticos y la dignidad humana.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP3' AND g.nombre = '4° Secundaria' LIMIT 1), 'Expresa opiniones razonadas sobre las consecuencias de sus decisiones, y propone acciones basadas en principios éticos y en la dignidad de las personas.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP4' AND g.nombre = '4° Secundaria' LIMIT 1), 'Se relaciona con mujeres y varones con equidad y respeto rechazando toda forma de discriminación por identidad de género u orientación sexual. Explica la importancia de establecer vínculos afectivos positivos basados en la reciprocidad, el cuidado del otro y el consentimiento. Rechaza la violencia familiar, sexual y contra la mujer, u otra forma de violencia.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP4' AND g.nombre = '4° Secundaria' LIMIT 1), 'Realiza acciones para prevenir y protegerse de situaciones que puedan afectar su integridad sexual y la de los demás. Ejemplo: Frente a una situación de acoso callejero, con la ayuda de un adulto de confianza, denuncia al agresor a la policía.'),

-- -------------------------------------------------------------
-- 5to Secundaria - DPCC-C1
-- -------------------------------------------------------------
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP1' AND g.nombre = '5° Secundaria' LIMIT 1), 'Evalúa las características personales, culturales, sociales y éticas que lo hacen único considerando su proyecto y sentido de vida. Describe sus logros, potencialidades y limitaciones. Muestra disposición para utilizar sus potencialidades en situaciones de riesgo (por ejemplo, la drogadicción).'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP1' AND g.nombre = '5° Secundaria' LIMIT 1), 'Expresa una postura crítica sobre sus practices culturales, las del país y las del mundo, valora su herencia cultural y natural y explica cómo la pertenencia a diversos grupos (culturales, religiosos, ambientales, de género, étnicos, políticos, etc.) influye en la construcción de su identidad.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP2' AND g.nombre = '5° Secundaria' LIMIT 1), 'Manifiesta sus emociones, sentimientos y comportamientos según el contexto y las personas. Explica sus causas y consecuencias, y utiliza estrategias de autorregulación que le permiten establecer relaciones justas.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP3' AND g.nombre = '5° Secundaria' LIMIT 1), 'Sustenta, con argumentos razonados, una posición ética frente a situaciones de conflicto moral considerando principios éticos, los derechos humanos y la dignidad humana.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP3' AND g.nombre = '5° Secundaria' LIMIT 1), 'Expresa puntos de vista razonados sobre las consecuencias de sus decisiones, y, para mejorar su comportamiento, propone acciones basadas en principios éticos, en la responsabilidad y en la justicia.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP4' AND g.nombre = '5° Secundaria' LIMIT 1), 'Interactúa con los demás mostrando respeto por las formas de vivir y pensar la sexualidad de mujeres y varones en un marco de derechos. Explica la importancia de aceptar y comprender su sexualidad para su desarrollo personal, y de tomar decisiones responsables en su proyecto de vida. Rechaza toda expresión de discriminación por identidad de género u orientación sexual que vulnere la dignidad de las personas.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP4' AND g.nombre = '5° Secundaria' LIMIT 1), 'Evalúa los vínculos de amistad o de pareja que establecen las personas como expresión de su sexualidad.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C1-CAP4' AND g.nombre = '5° Secundaria' LIMIT 1), 'Realiza acciones de prevención y protección frente a situaciones que puedan vulnerar los derechos sexuales y reproductivos en su escuela y comunidad.'),

-- -------------------------------------------------------------
-- 1ro Secundaria - DPCC-C2
-- -------------------------------------------------------------
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP1' AND g.nombre = '1° Secundaria' LIMIT 1), 'Establece relaciones basadas en el respeto y el diálogo con sus compañeros y compañeras, cuestiona los prejuicios y estereotipos más comunes que se dan en su entorno, y cumple sus deberes en la escuela.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP1' AND g.nombre = '1° Secundaria' LIMIT 1), 'Intercambia costumbres mostrando respeto por las diferencias.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP2' AND g.nombre = '1° Secundaria' LIMIT 1), 'Evalúa los acuerdos y las normas que regulan la convivencia en su escuela en función de si se basan en los derechos y deberes del niño y del adolescente.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP3' AND g.nombre = '1° Secundaria' LIMIT 1), 'Interviene ante conflictos cercanos a él utilizando el diálogo y la negociación.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP4' AND g.nombre = '1° Secundaria' LIMIT 1), 'Delibera sobre asuntos públicos cuando obtiene información de diversas fuentes, sustenta su posición sobre la base de argumentos y aporta a la construcción de consensos que contribuyan al bien común.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP5' AND g.nombre = '1° Secundaria' LIMIT 1), 'Propone acciones colectivas en la escuela en apoyo a grupos vulnerables en situación de desventaja social y económica tomando como base los derechos del niño.'),

-- -------------------------------------------------------------
-- 2do Secundaria - DPCC-C2
-- -------------------------------------------------------------
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP1' AND g.nombre = '2° Secundaria' LIMIT 1), 'Demuestra actitudes de respeto por sus compañeros, defiende sus derechos ante situaciones de vulneración, y cuestiona los prejuicios y estereotipos por etnia, género, ciclo vital o discapacidad más comunes de su entorno. Cumple sus deberes en la escuela y localidad, y promueve que los demás también los cumplan.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP1' AND g.nombre = '2° Secundaria' LIMIT 1), 'Intercambia costumbres mostrando respeto por las diferencias.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP2' AND g.nombre = '2° Secundaria' LIMIT 1), 'Propone normas que regulan la convivencia en la escuela y el uso responsable de las vías públicas de su localidad. Evalúa esas normas críticamente a partir de los principios democráticos y las modifica cuando se contraponen con sus derechos.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP3' AND g.nombre = '2° Secundaria' LIMIT 1), 'Actúa como mediador en conflictos de sus compañeros haciendo uso de habilidades sociales, el diálogo y la negociación.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP4' AND g.nombre = '2° Secundaria' LIMIT 1), 'Delibera sobre asuntos públicos cuando indaga sus causas y consecuencias, examina argumentos contrarios a los propios, y sustenta su posición basándose en principios democráticos y valores cívicos. Aporta a la construcción de consensos que contribuyan al bien común.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP5' AND g.nombre = '2° Secundaria' LIMIT 1), 'Participa cooperativamente en la planeación y ejecución de acciones en defensa de los derechos de la niñez. Asimismo, cumple responsablemente sus deberes y responsabilidades.'),

-- -------------------------------------------------------------
-- 3ro Secundaria - DPCC-C2
-- -------------------------------------------------------------
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP1' AND g.nombre = '3° Secundaria' LIMIT 1), 'Realiza acciones en el aula y la escuela que promueven integración de todos sus compañeros y compañeras, y cuestiona los prejuicios y estereotipos culturales más comunes entre adolescentes que se dan en los espacios públicos. Cumple sus deberes con sus pares y evalúa sus actions tomando en cuenta los valores cívicos y el bien común.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP1' AND g.nombre = '3° Secundaria' LIMIT 1), 'Intercambia prácticas culturales en relación a estilos de vida mostrando respeto por las diferencias.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP2' AND g.nombre = '3° Secundaria' LIMIT 1), 'Evalúa los acuerdos y las normas de convivencia a partir del criterio del bien común y los acepta. Expresa argumentos a favor del respeto por las normas y señales de tránsito para promover el uso seguro de las vías públicas.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP3' AND g.nombre = '3° Secundaria' LIMIT 1), 'Diferencia conflictos originados por la dinámica de las relaciones humanas de aquellos generados por su estancamiento. Utiliza estrategias diversas y creativas para prevenir y enfrentar conflictos.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP4' AND g.nombre = '3° Secundaria' LIMIT 1), 'Delibera sobre asuntos públicos cuando sustenta su posición a partir de la contraposición de puntos de vista distintos del suyo y del análisis de las diversas posturas y los posibles intereses involucrados. Aporta a la construcción de consensos que contribuyan al bien común de la nación peruana y del mundo.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP5' AND g.nombre = '3° Secundaria' LIMIT 1), 'Participa en acciones colectivas orientadas al bien común de la nación peruana, y a la promoción y defensa de los derechos humanos (civiles, políticos, económicos, sociales, culturales, ambientales, entre otros).'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP5' AND g.nombre = '3° Secundaria' LIMIT 1), 'Utiliza los mecanismos de participación estudiantil para evaluar la gestión de sus autoridades escolares.'),

-- -------------------------------------------------------------
-- 4to Secundaria - DPCC-C2
-- -------------------------------------------------------------
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP1' AND g.nombre = '4° Secundaria' LIMIT 1), 'Justifica la necesidad de rechazar conductas de violencia, marginación y explotación que puedan afectar a determinados grupos vulnerables de todas las edades y ciclos vitales por factores étnicos, de género, de origen, de lengua, de discapacidad, entre otros. Reconoce como sujetos de derechos a esos grupos. Cumple sus deberes y evalúa las consecuencias de sus acciones tomando en cuenta la dignidad humana.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP1' AND g.nombre = '4° Secundaria' LIMIT 1), 'Intercambia prácticas culturales en relación al sentido de autoridad y de gobierno, mostrando respeto por las diferencias.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP2' AND g.nombre = '4° Secundaria' LIMIT 1), 'Evalúa acuerdos y normas para una convivencia armónica y la promoción de la seguridad vial en su región, y propone normas sobre la base de los principios democráticos y los derechos humanos. Expresa argumentos sobre la importancia que tiene el Estado como institución que garantiza el cumplimiento de las leyes y la defensa nacional en el marco del Estado de derecho.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP3' AND g.nombre = '4° Secundaria' LIMIT 1), 'Explica las características de los diversos tipos de conflicto que se dan en la escuela y la comunidad, y los procedimientos que se deben seguir para su manejo. Utiliza mecanismos como la mediación, la conciliación y el arbitraje.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP4' AND g.nombre = '4° Secundaria' LIMIT 1), 'Delibera sobre asuntos públicos que afectan el sistema democrático, la institucionalidad y el Estado de derecho cuando sustenta su posición a partir de la contraposición de puntos de vista distintos del suyo, y sobre la base del análisis de las diversas posturas y los posibles intereses involucrados. Aporta a la construcción de consensos que contribuyan al bien común basándose en principios democráticos.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP5' AND g.nombre = '4° Secundaria' LIMIT 1), 'Participa en acciones colectivas orientadas al bien común a través de la promoción de los derechos de determinados grupos vulnerables (adultos mayores, discapacitados, miembros de pueblos originarios) y de los mecanismos de participación ciudadana.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP5' AND g.nombre = '4° Secundaria' LIMIT 1), 'Sustenta la pertinencia de recurrir a las correspondientes instancias frente a casos de vulneración de los derechos.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP5' AND g.nombre = '4° Secundaria' LIMIT 1), 'Evalúa el ejercicio del poder de sus autoridades considerando los derechos humanos y utilizando los mecanismos de participación ciudadana.'),

-- -------------------------------------------------------------
-- 5to Secundaria - DPCC-C2
-- -------------------------------------------------------------
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP1' AND g.nombre = '5° Secundaria' LIMIT 1), 'Demuestra actitudes de respeto por las personas con necesidades educativas especiales y por personas pertenecientes a culturas distintas de la suya. Rechaza situaciones de discriminación que puedan afectar los derechos de los grupos vulnerables. Cumple sus deberes en la escuela y evalúa sus acciones tomando en cuenta los principios democráticos.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP1' AND g.nombre = '5° Secundaria' LIMIT 1), 'Intercambia prácticas culturales en relación a las concepciones del mundo y de la vida, mostrando respeto y tolerancia por las diferencias.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP2' AND g.nombre = '5° Secundaria' LIMIT 1), 'Propone normas que regulan la convivencia y buscan evitar problemas de discriminación, basadas en la normatividad vigente a nivel nacional y mundial.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP2' AND g.nombre = '5° Secundaria' LIMIT 1), 'Explica que el Estado, para garantizar la convivencia, debe administrar justicia siempre en el marco de la legalidad.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP3' AND g.nombre = '5° Secundaria' LIMIT 1), 'Explica cómo se desarrolla la dinámica del conflicto y señala las actitudes que son fuente de este. Pone en práctica su rol de mediador para el manejo de conflictos.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP4' AND g.nombre = '5° Secundaria' LIMIT 1), 'Delibera sobre asuntos públicos que afectan los derechos humanos, la seguridad y la defensa nacional cuando sustenta su posición a partir de la contraposición de puntos de vista distintos del suyo, y sobre la base del análisis de las diversas posturas y los posibles intereses involucrados. Aporta a la construcción de consensos que contribuyan al bien común basándose en principios democráticos.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP5' AND g.nombre = '5° Secundaria' LIMIT 1), 'Realiza acciones participativas para promover y defender los derechos humanos y la justicia social y ambiental. Explica las funciones de los organismos e instituciones que velan por los derechos humanos en el Perú y el mundo.'),
((SELECT d.id FROM desempenos d JOIN capacidades c ON d.capacidad_id = c.id JOIN grados g ON d.grado_id = g.id WHERE c.codigo = 'DPCC-C2-CAP5' AND g.nombre = '5° Secundaria' LIMIT 1), 'Evalúa los procedimientos de las instituciones y organismos del Estado considerando el respeto por la dignidad humana, y propone alternativas para su mejora.');
