-- =====================================================
-- MIGRATION: Add Primaria Desempeños - Personal Social (PS) All Grades
-- 9 capacidades × 6 grados = 54 desempeños
-- =====================================================

-- PS 1° Primaria (9 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'PS-C1-CAP1-D1P', 'Describe sus características físicas, cualidades e intereses, y las diferencias con respecto a los demás. Ejemplo: El estudiante menciona que es bueno dibujando, que le gusta jugar fútbol, que es rápido corriendo, que tiene el pelo corto y negro, que es más alto que sus compañeros, etc.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'PS-C1-CAP2-D1P', 'Comparte las manifestaciones culturales, tradiciones y costumbres propias de su familia que hacen que se sienta orgulloso de su origen.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'PS-C1-CAP3-D1P', 'Describe las emociones a partir de su experiencia y de lo que observa en los demás, y las regula teniendo en cuenta normas establecidas de manera conjunta. Aplica estrategias de autorregulación (respiración), con la guía del docente.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'PS-C2-CAP1-D1P', 'Describe las características culturales que distinguen a su localidad o región (bailes, comidas, vestimenta, etc.) y las comparte.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'PS-C2-CAP2-D1P', 'Participa en actividades con sus compañeros respetando sus diferencias y cumpliendo con sus responsabilidades. Propone y colabora en acciones que promuevan el bienestar común.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'PS-C2-CAP3-D1P', 'Delibera sobre asuntos de interés común enfatizando en los que se generan durante la convivencia diaria en el aula, para proponer y participar en actividades colectivas orientadas al bienestar de todos, a partir de la identificación de necesidades.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'PS-C3-CAP1-D1P', 'Obtiene información sobre el pasado de algún hecho o suceso cotidiano a partir del testimonio oral de dos o más personas, y de objetos en desuso, fotografías, etc.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'PS-C3-CAP2-D1P', 'Secuencia acciones o hechos cotidianos de su vida personal, familiar y de la comunidad, y reconoce aquellos que suceden de manera simultánea.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'PS-C3-CAP3-D1P', 'Describe acontecimientos de su historia y de la comunidad a partir de objetos, imágenes y testimonios de personas, en los que compara el presente y el pasado; identifica algunas causas y consecuencias de estos.');

-- PS 2° Primaria (9 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'PS-C1-CAP1-D2P', 'Describe sus características físicas, habilidades y cualidades, y las diferencias con respecto a los demás. Comparte sus gustos, preferencias y aspiraciones.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'PS-C1-CAP2-D2P', 'Comparte las manifestaciones culturales, tradiciones y costumbres propias de su familia y comunidad que hacen que se sienta orgulloso de su origen.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'PS-C1-CAP3-D2P', 'Describe las emociones a partir de su experiencia y de lo que observa en los demás, y las regula teniendo en cuenta normas establecidas de manera conjunta. Aplica estrategias de autorregulación (respiración, distanciamiento, relajación y visualización).'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'PS-C2-CAP1-D2P', 'Describe las características culturales que distinguen a su localidad o región (bailes, comidas, vestimenta, etc.) y las comparte. Identifica su pertenencia a diversos grupos sociales (familia, escuela, comunidad).'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'PS-C2-CAP2-D2P', 'Participa en actividades con sus compañeros respetando sus diferencias y cumpliendo con sus responsabilidades. Propone y colabora en acciones que promuevan el bienestar común, reconociendo que las personas tienen los mismos derechos.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'PS-C2-CAP3-D2P', 'Delibera sobre asuntos de interés común enfatizando en los que se generan durante la convivencia diaria en el aula, para proponer y participar en actividades colectivas orientadas al bienestar de todos, a partir de la identificación de necesidades.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'PS-C3-CAP1-D2P', 'Obtiene información sobre el pasado de algún hecho o suceso cotidiano a partir del testimonio oral de dos o más personas, y de objetos en desuso, fotografías, imágenes antiguas, etc.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'PS-C3-CAP2-D2P', 'Secuencia acciones o hechos cotidianos de su vida personal, familiar y de la comunidad, y reconoce aquellos que suceden de manera simultánea. Elabora diagramas de secuencia utilizando meses y años.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'PS-C3-CAP3-D2P', 'Describe acontecimientos de su historia y de la comunidad a partir de objetos, imágenes y testimonios de personas, en los que compara el presente y el pasado; identifica algunas causas y posibles consecuencias de estos.');

-- PS 3° Primaria (9 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'PS-C1-CAP1-D3P', 'Describe aquellas características personales, cualidades, habilidades y logros que hacen que se sienta orgulloso de sí mismo. Comparte sus intereses, preferencias y aspiraciones.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'PS-C1-CAP2-D3P', 'Explica las manifestaciones culturales, tradiciones y costumbres propias de su familia, escuela y comunidad que hacen que se sienta orgulloso de su origen.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'PS-C1-CAP3-D3P', 'Describe las emociones en situaciones cotidianas; reconoce sus causas y consecuencias. Aplica estrategias de autorregulación (respiración, distanciamiento, relajación y visualización).'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'PS-C2-CAP1-D3P', 'Describe las características culturales que distinguen al pueblo de origen de su familia (bailes, comidas, vestimenta, etc.) y las comparte. Identifica su pertenencia a diversos grupos sociales (familia, escuela, comunidad, país).'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'PS-C2-CAP2-D3P', 'Participa en actividades con sus compañeros respetando sus diferencias y cumpliendo con sus responsabilidades. Propone y colabora en acciones que promuevan el bienestar común, reconociendo que las personas tienen los mismos derechos y responsabilidades.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'PS-C2-CAP3-D3P', 'Delibera sobre asuntos de interés común enfatizando en los que se generan durante la convivencia diaria en el aula, para proponer y participar en actividades colectivas orientadas al reconocimiento y respeto de sus derechos como niños y niñas, a partir de situaciones cotidianas.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'PS-C3-CAP1-D3P', 'Obtiene información acerca del proceso del poblamiento americano y de las primeras bandas a las primeras aldeas en el Perú, en textos cortos, así como en edificios antiguos o conjuntos arqueológicos de la localidad.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'PS-C3-CAP2-D3P', 'Secuencia imágenes, objetos o hechos utilizando categorías temporales (antes, ahora y después; años, décadas y siglos); elabora líneas de tiempo sencillas.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'PS-C3-CAP3-D3P', 'Describe algunas características que muestran el cambio y la permanencia en diversos aspectos de la vida cotidiana y de la historia del poblamiento americano hasta el proceso de sedentarización. Identifica distintos ritmos de cambio en diferentes objetos.');

-- PS 4° Primaria (9 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'PS-C1-CAP1-D4P', 'Describe aquellas características personales, cualidades, habilidades y logros que hacen que se sienta orgulloso de sí mismo. Comparte sus intereses, preferencias, aspiraciones y se reconoce como integrante de una colectividad.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'PS-C1-CAP2-D4P', 'Explica las manifestaciones culturales, tradiciones y costumbres propias de su familia, escuela y comunidad, y reconoce que aportan a la diversidad cultural del país.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'PS-C1-CAP3-D4P', 'Describe las emociones en situaciones cotidianas; reconoce sus causas y consecuencias. Aplica estrategias de autorregulación (respiración, distanciamiento, relajación, visualización y reestructuración cognitiva).'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'PS-C2-CAP1-D4P', 'Describe las características culturales que distinguen al pueblo de origen de su familia (bailes, comidas, vestimenta, etc.) y las comparte. Identifica su pertenencia a diversos grupos sociales (familia, escuela, comunidad, región, país) y explica cómo estos grupos definen parte de su identidad.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'PS-C2-CAP2-D4P', 'Participa en actividades con sus compañeros respetando sus diferencias y cumpliendo con sus responsabilidades. Propone y colabora en acciones que promuevan el bienestar común, reconociendo que las personas tienen los mismos derechos y responsabilidades. Evalúa el cumplimiento de sus responsabilidades y las de sus compañeros.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'PS-C2-CAP3-D4P', 'Delibera sobre asuntos de interés público para proponer y participar en actividades colectivas orientadas al bien común, reconociendo que existen opiniones distintas a la suya.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'PS-C3-CAP1-D4P', 'Obtiene información acerca de un hecho o proceso histórico, desde el origen de las primeras aldeas hasta las civilizaciones del Perú antiguo, a partir de cuadros estadísticos, gráficos sencillos o investigaciones realizadas.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'PS-C3-CAP2-D4P', 'Secuencia distintos hechos de la historia local, regional y nacional del Perú antiguo y los ubica en distintos momentos del tiempo histórico, empleando categorías temporales como años, décadas y siglos. Elabora líneas de tiempo.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'PS-C3-CAP3-D4P', 'Identifica cambios y permanencias en distintos aspectos de la vida cotidiana y de la historia del Perú antiguo. Identifica distintos ritmos de cambio en diferentes objetos.');

-- PS 5° Primaria (9 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'PS-C1-CAP1-D5P', 'Describe sus características personales, cualidades, habilidades y logros, y las utiliza para definir y fortalecer su identidad con relación a su familia, amigos, escuela y comunidad.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'PS-C1-CAP2-D5P', 'Explica las manifestaciones culturales, tradiciones y costumbres propias de su familia, escuela y comunidad, y reconoce que aportan a la diversidad cultural del país. Explica la importancia de conservar y respetar esta diversidad.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'PS-C1-CAP3-D5P', 'Explica las causas y consecuencias de sus emociones y sentimientos, en sí mismo y en los demás, en situaciones reales e hipotéticas. Utiliza estrategias de autorregulación (respiración, distanciamiento, relajación, visualización y reestructuración cognitiva).'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'PS-C2-CAP1-D5P', 'Describe las características culturales que distinguen al pueblo de origen de su familia (bailes, comidas, vestimenta, etc.) y las comparte. Identifica su pertenencia a diversos grupos sociales (familia, escuela, comunidad, región, país) y explica cómo estos grupos definen parte de su identidad y contribuyen a su desarrollo y al de los demás.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'PS-C2-CAP2-D5P', 'Participa en actividades con sus compañeros respetando sus diferencias y cumpliendo con sus responsabilidades. Propone y colabora en acciones que promuevan el bienestar común, la defensa de sus derechos y el cumplimiento de sus responsabilidades como miembro de una comunidad. Evalúa el cumplimiento de sus responsabilidades y las de sus compañeros, y propone cómo mejorarlo.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'PS-C2-CAP3-D5P', 'Delibera sobre asuntos de interés público para proponer y participar en actividades colectivas orientadas al bien común, a partir de situaciones cotidianas, y reconoce que existen opiniones distintas a la suya.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'PS-C3-CAP1-D5P', 'Obtiene información sobre un hecho o proceso histórico, desde las invasiones bárbaras hasta la Edad Media, a partir de cuadros estadísticos, gráficos sencillos o investigaciones realizadas.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'PS-C3-CAP2-D5P', 'Secuencia distintos hechos de la historia local, regional, nacional y mundial, y los ubica en distintos momentos del tiempo histórico, empleando categorías temporales como años, décadas y siglos. Elabora líneas de tiempo paralelas, identificando hechos y procesos.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'PS-C3-CAP3-D5P', 'Identifica cambios, permanencias y simultaneidades en distintos aspectos de la vida cotidiana y de la historia del Perú y de la humanidad, utilizando instrumentos y técnicas diversas.');

-- PS 6° Primaria (9 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'PS-C1-CAP1-D6P', 'Explica las características personales (cualidades, gustos, fortalezas y limitaciones) que tiene por ser parte de una familia, así como la contribución de esta a su formación personal y a su proyecto de vida.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'PS-C1-CAP2-D6P', 'Explica las manifestaciones culturales, tradiciones y costumbres propias de su familia, escuela y comunidad, y reconoce que aportan a la diversidad cultural del país. Explica la importancia de conservar y respetar esta diversidad, y de conocer los derechos del niño.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'PS-C1-CAP3-D6P', 'Explica las causas y consecuencias de sus emociones y sentimientos, en sí mismo y en los demás, en situaciones reales e hipotéticas. Utiliza estrategias de autorregulación (respiración, distanciamiento, relajación, visualización, reestructuración cognitiva y búsqueda de apoyo).'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'PS-C2-CAP1-D6P', 'Explica las características culturales que distinguen a diversos pueblos del Perú (bailes, comidas, vestimenta, etc.) y las comparte. Identifica su pertenencia a diversos grupos sociales (familia, escuela, comunidad, región, país, mundo) y explica cómo estos grupos definen parte de su identidad y contribuyen a su desarrollo y al de los demás.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'PS-C2-CAP2-D6P', 'Participa en actividades con sus compañeros respetando sus diferencias y cumpliendo con sus responsabilidades. Propone y colabora en acciones que promuevan el bienestar común, la defensa de sus derechos y el cumplimiento de sus responsabilidades como miembro de una comunidad. Evalúa el cumplimiento de sus responsabilidades y las de sus compañeros, y propone cómo mejorarlo, a partir de los principios democráticos.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'PS-C2-CAP3-D6P', 'Delibera sobre asuntos de interés público para proponer y participar en actividades colectivas orientadas al bien común, a partir de situaciones cotidianas, y reconoce que existen opiniones distintas a la suya y que estas pueden aportar al debate.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'PS-C3-CAP1-D6P', 'Obtiene información sobre un hecho o proceso histórico, desde el desarrollo del absolutismo (ss. XVI y XVII) hasta las revoluciones liberales del siglo XIX y la formación de los Estados latinoamericanos, a partir de cuadros estadísticos, gráficos sencillos o investigaciones realizadas.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'PS-C3-CAP2-D6P', 'Secuencia distintos hechos de la historia local, regional, nacional y mundial, y los ubica en distintos momentos del tiempo histórico, empleando categorías temporales como años, décadas y siglos. Elabora líneas de tiempo paralelas, identificando hechos, procesos, duraciones y simultaneidades.'),
((SELECT id FROM capacidades WHERE codigo = 'PS-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'PS-C3-CAP3-D6P', 'Identifica cambios, permanencias y simultaneidades en distintos aspectos de la vida cotidiana y de la historia del Perú y de la humanidad, utilizando instrumentos y técnicas diversas, y explica las relaciones que se dan entre ellos.');
