-- =====================================================
-- MIGRATION: Add Primaria Desempeños - Phase 1 Part 2
-- Areas: Comunicación (4°-6°), Ciencia y Tecnología (1°-6°), Personal Social (1°-6°)
-- =====================================================

-- COMUNICACIÓN - Grados 4°, 5°, 6° (13 desempeños por grado = 39 total)

-- 4° Primaria - Comunicación
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C1-CAP1-D4P', 'Obtiene información explícita, relevante y complementaria, en distintas partes del texto oral, distinguiéndola de otra cercana y semejante, en diversos tipos de textos orales con vocabulario variado.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C1-CAP2-D4P', 'Infiere información deduciendo características implícitas de seres, objetos, hechos y lugares, y determinando el significado de palabras según el contexto y haciendo comparaciones, así como el tema y propósito del texto oral.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C1-CAP3-D4P', 'Adecúa su texto oral a la situación comunicativa, de acuerdo al propósito comunicativo, al tipo textual y a algunas características del género discursivo, manteniendo el registro formal e informal y adaptándose a sus interlocutores.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C1-CAP4-D4P', 'Expresa oralmente ideas y emociones en torno a un tema, de forma coherente y cohesionada, ordenando y jerarquizando las ideas, estableciendo relaciones lógicas entre ellas y utilizando conectores y algunos referentes.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C1-CAP5-D4P', 'Interactúa estratégicamente con distintos interlocutores, participando en diversos intercambios orales, formulando preguntas sobre lo que le interesa saber, dando respuestas y haciendo comentarios relacionados con el tema.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP6'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C1-CAP6-D4P', 'Reflexiona y evalúa como hablante y oyente la forma, el contenido y contexto del texto oral, opinando sobre las ideas del interlocutor y evaluando la eficacia de los recursos verbales, no verbales y paraverbales.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C2-CAP1-D4P', 'Obtiene información explícita, relevante y complementaria, en distintas partes del texto escrito, distinguiéndola de otra cercana y semejante, en diversos tipos de textos con varios elementos complejos y vocabulario variado.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C2-CAP2-D4P', 'Infiere información deduciendo características implícitas de seres, objetos, hechos y lugares, y determinando el significado de palabras según el contexto y haciendo comparaciones, así como el tema, subtemas, la idea principal y el propósito del texto.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C2-CAP3-D4P', 'Reflexiona y evalúa los textos escritos, opinando acerca del contenido y explicando el sentido de algunos recursos textuales y la intención del autor, a partir de su experiencia y del contexto sociocultural.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C3-CAP1-D4P', 'Adecúa el texto a la situación comunicativa considerando el propósito comunicativo, el tipo textual y algunas características del género discursivo, así como el formato y el soporte, manteniendo el registro formal e informal según los interlocutores.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C3-CAP2-D4P', 'Organiza y desarrolla las ideas de forma coherente y cohesionada, estableciendo relaciones lógicas entre ellas (en especial, de adición, secuencia, causa-efecto y consecuencia) a través del uso adecuado de conectores y referentes.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C3-CAP3-D4P', 'Utiliza convenciones del lenguaje escrito de forma pertinente, usando recursos gramaticales y ortográficos (coma enumerativa, dos puntos, guiones en diálogos, guiones en enumeraciones) que contribuyen al sentido de su texto.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'COM-C3-CAP4-D4P', 'Reflexiona y evalúa de manera permanente el texto que escribe, revisando si se adecúa a la situación comunicativa, si las ideas son coherentes y cohesionadas, y si el uso de conectores, referentes y recursos ortográficos asegura la claridad del texto.');

-- 5° Primaria - Comunicación
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C1-CAP1-D5P', 'Obtiene información explícita, relevante y complementaria, compara información ubicada en distintas partes del texto oral, distinguiéndola de otra cercana y semejante, en diversos tipos de textos orales con vocabulario variado.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C1-CAP2-D5P', 'Infiere información deduciendo diversas relaciones lógicas entre las ideas del texto oral (causa-efecto, semejanza-diferencia, entre otras), el tema central, la idea principal, el propósito, las conclusiones y la intención del interlocutor.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C1-CAP3-D5P', 'Adecúa su texto oral a la situación comunicativa, de acuerdo al propósito comunicativo, al tipo textual, a las características del género discursivo, manteniendo el registro formal e informal y adaptándose a sus interlocutores y al contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C1-CAP4-D5P', 'Expresa oralmente ideas y emociones de forma coherente y cohesionada, ordenando y jerarquizando las ideas, estableciendo diversas relaciones lógicas entre ellas a través del uso preciso de conectores y algunos referentes.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C1-CAP5-D5P', 'Interactúa estratégicamente con distintos interlocutores, participando en diversos intercambios orales, formulando y respondiendo preguntas, explicando y complementando las ideas expuestas, utilizando un vocabulario pertinente.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP6'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C1-CAP6-D5P', 'Reflexiona y evalúa como hablante y oyente la forma, el contenido y contexto del texto oral, opinando sobre las ideas, la adecuación del texto a la situación comunicativa y la eficacia de los recursos verbales, no verbales y paraverbales utilizados.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C2-CAP1-D5P', 'Obtiene información explícita, relevante y complementaria, comparando información ubicada en distintas partes del texto escrito, distinguiéndola de otra cercana y semejante, en diversos tipos de textos con varios elementos complejos y vocabulario variado.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C2-CAP2-D5P', 'Infiere información deduciendo diversas relaciones lógicas entre las ideas del texto escrito (causa-efecto, semejanza-diferencia, entre otras), el tema central, subtemas, la idea principal, el propósito, las conclusiones y la intención del autor.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C2-CAP3-D5P', 'Reflexiona y evalúa los textos escritos, opinando acerca del contenido, la organización textual, el sentido de diversos recursos textuales y la intención del autor, evaluando los efectos del texto en los lectores a partir de su experiencia y del contexto sociocultural.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C3-CAP1-D5P', 'Adecúa el texto a la situación comunicativa considerando el propósito comunicativo, el tipo textual, las características del género discursivo, el formato y el soporte, manteniendo el registro formal e informal según los interlocutores y el propósito.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C3-CAP2-D5P', 'Organiza y desarrolla las ideas de forma coherente y cohesionada, estableciendo diversas relaciones lógicas entre ellas a través del uso preciso de conectores y referentes, y utilizando recursos gramaticales y ortográficos que contribuyen al sentido del texto.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C3-CAP3-D5P', 'Utiliza convenciones del lenguaje escrito de forma pertinente, usando de manera precisa recursos gramaticales y ortográficos (puntos suspensivos, comillas, guiones) que contribuyen al sentido y claridad de su texto.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'COM-C3-CAP4-D5P', 'Reflexiona y evalúa de manera permanente el texto que escribe, revisando si se adecúa a la situación comunicativa, si las ideas son coherentes y cohesionadas, y si el uso de conectores, referentes y recursos ortográficos asegura la claridad y el sentido del texto.');

-- 6° Primaria - Comunicación
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C1-CAP1-D6P', 'Obtiene información explícita, relevante y complementaria, seleccionando datos específicos y algunos detalles en diversos tipos de textos orales con vocabulario variado, comparando información y realizando inferencias a partir de los datos obtenidos.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C1-CAP2-D6P', 'Infiere información deduciendo diversas relaciones lógicas entre las ideas del texto oral (causa-efecto, semejanza-diferencia, entre otras), el tema central, la idea principal, el propósito, las conclusiones, la intención del interlocutor y las características de seres, objetos, hechos y lugares.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C1-CAP3-D6P', 'Adecúa su texto oral a la situación comunicativa considerando el propósito comunicativo, el tipo textual, las características del género discursivo, el registro formal e informal, adaptándose a sus interlocutores, al contexto y utilizando recursos no verbales y paraverbales para enfatizar lo que dice.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C1-CAP4-D6P', 'Expresa oralmente ideas y emociones de forma coherente y cohesionada, ordenando y jerarquizando las ideas, estableciendo diversas relaciones lógicas entre ellas a través del uso preciso de diversos conectores y referentes, y utilizando vocabulario variado y pertinente.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C1-CAP5-D6P', 'Interactúa estratégicamente con distintos interlocutores, participando en diversos intercambios orales, formulando y respondiendo preguntas, explicando, complementando y contrastando las ideas expuestas, utilizando un vocabulario pertinente y recurriendo a normas y modos de cortesía.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP6'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C1-CAP6-D6P', 'Reflexiona y evalúa como hablante y oyente la forma, el contenido y contexto del texto oral, opinando sobre las ideas, la adecuación del texto a la situación comunicativa, la eficacia de los recursos verbales, no verbales y paraverbales utilizados, y la validez de la información.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C2-CAP1-D6P', 'Obtiene información explícita, relevante y complementaria, seleccionando datos específicos y algunos detalles en diversos tipos de textos escritos con varios elementos complejos y vocabulario variado, comparando información y realizando inferencias a partir de los datos obtenidos.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C2-CAP2-D6P', 'Infiere información deduciendo diversas relaciones lógicas entre las ideas del texto escrito (causa-efecto, semejanza-diferencia, entre otras), el tema central, subtemas, la idea principal, el propósito, las conclusiones, la intención del autor y las características de seres, objetos, hechos y lugares.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C2-CAP3-D6P', 'Reflexiona y evalúa los textos escritos, opinando acerca del contenido, la organización textual, el sentido de diversos recursos textuales, la intención del autor y el efecto del texto en los lectores, evaluando la validez de la información a partir de su experiencia y del contexto sociocultural.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C3-CAP1-D6P', 'Adecúa el texto a la situación comunicativa considerando el propósito comunicativo, el tipo textual, las características del género discursivo, el formato y el soporte, manteniendo el registro formal e informal según los interlocutores, el propósito y el tema, y utilizando un vocabulario pertinente.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C3-CAP2-D6P', 'Organiza y desarrolla las ideas de forma coherente y cohesionada, estableciendo diversas relaciones lógicas entre ellas a través del uso preciso de diversos conectores y referentes, y utilizando recursos gramaticales y ortográficos que contribuyen al sentido y claridad del texto.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C3-CAP3-D6P', 'Utiliza convenciones del lenguaje escrito de forma pertinente, usando de manera precisa diversos recursos gramaticales y ortográficos (puntos suspensivos, comillas, guiones, tildación) que contribuyen al sentido, claridad y estilo de su texto.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'COM-C3-CAP4-D6P', 'Reflexiona y evalúa de manera permanente el texto que escribe, revisando si se adecúa a la situación comunicativa, si las ideas son coherentes y cohesionadas, si el uso de conectores, referentes y recursos ortográficos asegura la claridad y el sentido del texto, y si es efectivo según su propósito.');
