-- =====================================================
-- MIGRATION: Add Primaria Desempeños - Phase 3 Part 1: Inglés
-- ING: 13 capacidades × 6 grados = 78 desempeños
-- Competencias:
--   C1: Se comunica oralmente en inglés (6 capacidades)
--   C2: Lee diversos tipos de textos en inglés (3 capacidades)
--   C3: Escribe diversos tipos de textos en inglés (4 capacidades)
-- =====================================================

-- INGLÉS 1° PRIMARIA (13 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
-- Competencia 1: Se comunica oralmente en inglés
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C1-CAP1-D1P', 'Recupera y reúne información explícita en los textos orales que escucha en inglés, en situaciones comunicativas cotidianas, con vocabulario sencillo; para ello, se apoya en lenguaje audiovisual, gestos y expresiones corporales del emisor.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C1-CAP2-D1P', 'Deduce información señalando características de personas, animales, objetos, lugares de su entorno inmediato y comunidad; así como el significado de palabras, frases y expresiones básicas en textos orales de estructura simple en inglés.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C1-CAP3-D1P', 'Expresa sus ideas en torno a un tema en coherencia con su nivel y utiliza vocabulario de uso frecuente dentro de su entorno familiar y escolar.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C1-CAP4-D1P', 'Utiliza recursos no verbales como gestos y expresiones corporales, tono y volumen de voz apropiados para su texto oral en inglés.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C1-CAP5-D1P', 'Participa en situaciones comunicativas cotidianas en las que alterna los roles de hablante y oyente, para preguntar y responder en inglés con vocabulario simple; recurre a modos de cortesía según el contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP6'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C1-CAP6-D1P', 'Opina en inglés sobre lo comprendido del texto oral e indica lo que le gustó a partir de su experiencia y el contexto en el que se desenvuelve.'),
-- Competencia 2: Lee diversos tipos de textos en inglés
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C2-CAP1-D1P', 'Identifica información explícita que es claramente distinguible de otra y que se encuentra en lugares evidentes, como título, inicio o final, en textos escritos en inglés, con vocabulario sencillo y con o sin ilustraciones.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C2-CAP2-D1P', 'Deduce relaciones lógicas (adición, contraste, secuencia, semejanza-diferencia y causa) en textos escritos en inglés. Señala información acerca de personas, animales, objetos y lugares, a partir de indicios como ilustraciones y silueta de texto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C2-CAP3-D1P', 'Opina en inglés de manera oral, escrita o mediante ilustraciones o recursos no verbales sobre el contenido de los textos escritos en inglés.'),
-- Competencia 3: Escribe diversos tipos de textos en inglés
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C3-CAP1-D1P', 'Adecúa el texto que escribe en inglés a la situación comunicativa considerando el propósito y el destinatario, recurriendo a su experiencia para escribir.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C3-CAP2-D1P', 'Produce textos escritos en inglés en torno a un tema con coherencia, cohesión y fluidez de acuerdo a su nivel, y organiza sus ideas para establecer relaciones lógicas (adición y contraste); amplía información de forma pertinente con vocabulario apropiado.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C3-CAP3-D1P', 'Emplea convenciones del lenguaje escrito como recursos ortográficos y gramaticales de mediana complejidad que le dan claridad y sentido al texto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ING-C3-CAP4-D1P', 'Revisa su texto en inglés para mejorarlo; considera algunos aspectos gramaticales y ortográficos básicos para dar sentido al texto.');

-- INGLÉS 2° PRIMARIA (13 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C1-CAP1-D2P', 'Recupera y reúne información explícita en los textos orales que escucha en inglés, en situaciones comunicativas cotidianas, con vocabulario sencillo; para ello, se apoya en lenguaje audiovisual, gestos y expresiones corporales del emisor.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C1-CAP2-D2P', 'Deduce información señalando características de personas, animales, objetos, lugares de su entorno inmediato y comunidad; así como el significado de palabras, frases y expresiones básicas en textos orales de estructura simple en inglés.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C1-CAP3-D2P', 'Expresa sus ideas en torno a un tema en coherencia con su nivel y utiliza vocabulario de uso frecuente dentro de su entorno familiar y escolar.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C1-CAP4-D2P', 'Utiliza recursos no verbales como gestos y expresiones corporales, tono y volumen de voz apropiados para su texto oral en inglés.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C1-CAP5-D2P', 'Participa en situaciones comunicativas cotidianas en las que alterna los roles de hablante y oyente, para preguntar y responder en inglés con vocabulario simple; recurre a modos de cortesía según el contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP6'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C1-CAP6-D2P', 'Opina en inglés sobre lo comprendido del texto oral e indica lo que le gustó a partir de su experiencia y el contexto en el que se desenvuelve.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C2-CAP1-D2P', 'Identifica información explícita que es claramente distinguible de otra y que se encuentra en lugares evidentes, como título, inicio o final, en textos escritos en inglés, con vocabulario sencillo y con o sin ilustraciones.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C2-CAP2-D2P', 'Deduce relaciones lógicas (adición, contraste, secuencia, semejanza-diferencia y causa) en textos escritos en inglés. Señala información acerca de personas, animales, objetos y lugares, a partir de indicios como ilustraciones y silueta de texto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C2-CAP3-D2P', 'Opina en inglés de manera oral, escrita o mediante ilustraciones o recursos no verbales sobre el contenido de los textos escritos en inglés.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C3-CAP1-D2P', 'Adecúa el texto que escribe en inglés a la situación comunicativa considerando el propósito y el destinatario, recurriendo a su experiencia para escribir.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C3-CAP2-D2P', 'Produce textos escritos en inglés en torno a un tema con coherencia, cohesión y fluidez de acuerdo a su nivel, y organiza sus ideas para establecer relaciones lógicas (adición y contraste); amplía información de forma pertinente con vocabulario apropiado.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C3-CAP3-D2P', 'Emplea convenciones del lenguaje escrito como recursos ortográficos y gramaticales de mediana complejidad que le dan claridad y sentido al texto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ING-C3-CAP4-D2P', 'Revisa su texto en inglés para mejorarlo; considera algunos aspectos gramaticales y ortográficos básicos para dar sentido al texto.');

-- INGLÉS 3° PRIMARIA (13 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C1-CAP1-D3P', 'Recupera y ordena información explícita ubicada en distintas partes de los textos orales que escucha en inglés, en situaciones comunicativas diversas, con vocabulario de uso frecuente; para ello, se apoya en el contexto, el lenguaje audiovisual y los gestos del emisor.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C1-CAP2-D3P', 'Deduce información señalando características de personas, animales, objetos, lugares; así como el significado de palabras, frases y expresiones en textos orales de estructura simple en inglés (modal verb can - yes / No questions and answers; coordinating conjunctions - and, but; verb to be; present simple; action verbs; wh-questions - what, how, where, what color, what number; demonstrative pronouns - this, that; possessive pronouns - my, your, his, her; possessive adjectives; personal pronouns - I, you, it, she, he; adjectives - young, old, small, big, tall, short).'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C1-CAP3-D3P', 'Expresa sus ideas en torno a un tema de forma coherente y cohesionada, ordenándolas para establecer relaciones lógicas (adición y contraste) y ampliando información de forma pertinente con vocabulario apropiado.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C1-CAP4-D3P', 'Emplea gestos y movimientos para enfatizar lo que dice usando pronunciación y volumen adecuados; se apoya en material concreto y visual.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C1-CAP5-D3P', 'Participa en diversas situaciones comunicativas alternando los roles de hablante y oyente, para preguntar, responder, así como hacer comentarios relevantes en inglés con vocabulario de uso frecuente y pertinente; recurre a modos de cortesía según el contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP6'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C1-CAP6-D3P', 'Opina en inglés como hablante y oyente sobre el contenido y el propósito comunicativo del texto oral, y sobre las intenciones de los interlocutores a partir de su experiencia y el contexto en el que se desenvuelve.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C2-CAP1-D3P', 'Identifica información explícita que se encuentra en distintas partes del texto escrito en inglés, distinguiéndola de otra información semejante con elementos simples en su estructura y vocabulario de uso frecuente.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C2-CAP2-D3P', 'Deduce relaciones lógicas (adición, contraste, secuencia, semejanza-diferencia, causa-efecto) y jerárquicas (ideas principales) en textos escritos en inglés. Señala características de personas, animales, objetos y lugares, así como el significado de palabras, frases y expresiones en contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C2-CAP3-D3P', 'Opina en inglés de manera oral o escrita sobre el contenido y propósito comunicativo de los textos escritos en inglés, a partir de su experiencia y contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C3-CAP1-D3P', 'Adecúa el texto que escribe en inglés a la situación comunicativa considerando el propósito (obtener información de contacto; deletrear nombres; describir y comparar animales, objetos y lugares; describir actividades diarias, de recreación y el clima; expresar preferencias musicales y deportivas) y el destinatario.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C3-CAP2-D3P', 'Produce textos escritos en inglés en torno a un tema con coherencia, cohesión y fluidez de acuerdo a su nivel, organizándolas para establecer relaciones lógicas (adición y contraste) y ampliando información de forma pertinente con vocabulario apropiado.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C3-CAP3-D3P', 'Emplea convenciones del lenguaje escrito como recursos ortográficos y gramaticales de mediana complejidad que le dan claridad y sentido al texto. Ejemplo: modal verb can - yes / No questions and answers; coordinating conjunctions - and, but; verb to be; present simple; action verbs; wh-questions - what, how, where, what color, what number; demonstrative pronouns - this, that; possessive pronouns - my, your, his, her; possessive adjectives; personal pronouns - I, you, it, she, he; adjectives - young, old, small, big, tall, short.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ING-C3-CAP4-D3P', 'Revisa su texto en inglés para mejorarlo; considera algunos aspectos gramaticales y ortográficos básicos vinculados con el lenguaje escrito para dar sentido al texto.');

-- INGLÉS 4° PRIMARIA (13 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C1-CAP1-D4P', 'Recupera y ordena información explícita ubicada en distintas partes de los textos orales que escucha en inglés, en situaciones comunicativas diversas, con vocabulario de uso frecuente; para ello, se apoya en el contexto, el lenguaje audiovisual y los gestos del emisor.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C1-CAP2-D4P', 'Deduce información señalando características de personas, animales, objetos, lugares; así como el significado de palabras, frases y expresiones en textos orales de estructura simple en inglés (modal verb can - yes / No questions and answers; coordinating conjunctions - and, but; verb to be; present simple; action verbs; wh-questions - what, how, where, what color, what number; demonstrative pronouns - this, that; possessive pronouns - my, your, his, her; possessive adjectives; personal pronouns - I, you, it, she, he; adjectives - young, old, small, big, tall, short).'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C1-CAP3-D4P', 'Expresa sus ideas en torno a un tema de forma coherente y cohesionada, ordenándolas para establecer relaciones lógicas (adición y contraste) y ampliando información de forma pertinente con vocabulario apropiado.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C1-CAP4-D4P', 'Emplea gestos y movimientos para enfatizar lo que dice usando pronunciación y volumen adecuados; se apoya en material concreto y visual.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C1-CAP5-D4P', 'Participa en diversas situaciones comunicativas alternando los roles de hablante y oyente, para preguntar, responder, así como hacer comentarios relevantes en inglés con vocabulario de uso frecuente y pertinente; recurre a modos de cortesía según el contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP6'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C1-CAP6-D4P', 'Opina en inglés como hablante y oyente sobre el contenido y el propósito comunicativo del texto oral, y sobre las intenciones de los interlocutores a partir de su experiencia y el contexto en el que se desenvuelve.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C2-CAP1-D4P', 'Identifica información explícita que se encuentra en distintas partes del texto escrito en inglés, distinguiéndola de otra información semejante con elementos simples en su estructura y vocabulario de uso frecuente.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C2-CAP2-D4P', 'Deduce relaciones lógicas (adición, contraste, secuencia, semejanza-diferencia, causa-efecto) y jerárquicas (ideas principales) en textos escritos en inglés. Señala características de personas, animales, objetos y lugares, así como el significado de palabras, frases y expresiones en contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C2-CAP3-D4P', 'Opina en inglés de manera oral o escrita sobre el contenido y propósito comunicativo de los textos escritos en inglés, a partir de su experiencia y contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C3-CAP1-D4P', 'Adecúa el texto que escribe en inglés a la situación comunicativa considerando el propósito (obtener información de contacto; deletrear nombres; describir y comparar animales, objetos y lugares; describir actividades diarias, de recreación y el clima; expresar preferencias musicales y deportivas) y el destinatario.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C3-CAP2-D4P', 'Produce textos escritos en inglés en torno a un tema con coherencia, cohesión y fluidez de acuerdo a su nivel, organizándolas para establecer relaciones lógicas (adición y contraste) y ampliando información de forma pertinente con vocabulario apropiado.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C3-CAP3-D4P', 'Emplea convenciones del lenguaje escrito como recursos ortográficos y gramaticales de mediana complejidad que le dan claridad y sentido al texto. Ejemplo: modal verb can - yes / No questions and answers; coordinating conjunctions - and, but; verb to be; present simple; action verbs; wh-questions - what, how, where, what color, what number; demonstrative pronouns - this, that; possessive pronouns - my, your, his, her; possessive adjectives; personal pronouns - I, you, it, she, he; adjectives - young, old, small, big, tall, short.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ING-C3-CAP4-D4P', 'Revisa su texto en inglés para mejorarlo; considera algunos aspectos gramaticales y ortográficos básicos vinculados con el lenguaje escrito para dar sentido al texto.');

-- INGLÉS 5° PRIMARIA (13 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C1-CAP1-D5P', 'Recupera y ordena información explícita y relevante ubicada en distintas partes de los textos orales que escucha en inglés, en situaciones comunicativas diversas, con vocabulario de uso frecuente; para ello, se apoya en el contexto, el lenguaje audiovisual y los gestos del emisor.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C1-CAP2-D5P', 'Deduce información señalando características de personas, animales, objetos, lugares; el significado de palabras, frases y expresiones de estructura simple según el contexto (modal verb can - yes / No questions and answers; coordinating conjunctions - and, but; verb to be; present simple; action verbs; wh-questions - what, how, where, what color, what number; demonstrative pronouns - this, that, these, those; possessive pronouns - my, your, his, her; possessive adjectives; personal pronouns - I, you, it, she, he, we, they; adjectives - young, old, small, big, tall, short), así como relaciones lógicas (adición, contraste, secuencia, semejanza-diferencia y causa) y jerárquicas (ideas principales) en textos orales en inglés.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C1-CAP3-D5P', 'Expresa sus ideas y emociones en torno a un tema con coherencia, cohesión y fluidez de acuerdo con su nivel, organizándolas para establecer relaciones lógicas (adición, contraste, secuencia, semejanza-diferencia y causa) y ampliando la información de forma pertinente con vocabulario apropiado.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C1-CAP4-D5P', 'Emplea gestos y movimientos para enfatizar lo que dice usando pronunciación, entonación y volumen adecuados; se apoya en material concreto y visual.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C1-CAP5-D5P', 'Participa en diversas situaciones comunicativas alternando los roles de hablante y oyente, para preguntar, responder, explicar, así como hacer comentarios relevantes en inglés con vocabulario de uso frecuente y pertinente; recurre a modos de cortesía según el contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP6'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C1-CAP6-D5P', 'Opina en inglés como hablante y oyente sobre el contenido y el propósito comunicativo del texto oral, y sobre las intenciones de los interlocutores a partir de su experiencia y el contexto en el que se desenvuelve.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C2-CAP1-D5P', 'Identifica información explícita, relevante y complementaria distinguiéndola de otra cercana y semejante en diversos tipos de textos escritos en inglés con vocabulario de uso frecuente y pertinente.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C2-CAP2-D5P', 'Deduce relaciones lógicas (adición, contraste, secuencia, semejanza-diferencia, causa-efecto) y jerárquicas (ideas principales y complementarias) en textos escritos en inglés. Señala características de personas, animales, objetos, lugares, así como el significado de palabras, frases y expresiones en contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C2-CAP3-D5P', 'Opina en inglés de manera oral o escrita sobre el contenido y propósito comunicativo de los textos escritos en inglés, a partir de su experiencia y contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C3-CAP1-D5P', 'Adecúa el texto que escribe en inglés a la situación comunicativa considerando el tipo textual, algunas características del género discursivo, el formato, el soporte y el propósito.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C3-CAP2-D5P', 'Produce textos escritos en inglés en torno a un tema con coherencia, cohesión y fluidez de acuerdo con su nivel, organizándolas para establecer relaciones lógicas (adición, contraste, secuencia, semejanza-diferencia y causa) y ampliando información de forma pertinente con vocabulario apropiado.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C3-CAP3-D5P', 'Emplea convenciones del lenguaje escrito como recursos ortográficos y gramaticales de mediana complejidad que le dan claridad y sentido al texto. Ejemplo: modal verb can - yes / No questions and answers; coordinating conjunctions - and, but; verb to be; present simple; action verbs; wh-questions - what, how, where, what color, what number; demonstrative pronouns - this, that, these, those; possessive pronouns - my, your, his, her; possessive adjectives; personal pronouns - I, you, it, she, he, we, they; adjectives - young, old, small, big, tall, short.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ING-C3-CAP4-D5P', 'Revisa su texto en inglés para mejorarlo; considera aspectos gramaticales y ortográficos básicos vinculados con el lenguaje escrito para dar sentido al texto.');

-- INGLÉS 6° PRIMARIA (13 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C1-CAP1-D6P', 'Recupera y ordena información explícita y relevante ubicada en distintas partes de los textos orales que escucha en inglés, en situaciones comunicativas diversas, con vocabulario de uso frecuente; para ello, se apoya en el contexto, el lenguaje audiovisual y los gestos del emisor.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C1-CAP2-D6P', 'Deduce información señalando características de personas, animales, objetos, lugares; el significado de palabras, frases y expresiones de estructura simple según el contexto (modal verb can - yes / No questions and answers; coordinating conjunctions - and, but; verb to be; present simple; action verbs; wh-questions - what, how, where, what color, what number; demonstrative pronouns - this, that, these, those; possessive pronouns - my, your, his, her; possessive adjectives; personal pronouns - I, you, it, she, he, we, they; adjectives - young, old, small, big, tall, short), así como relaciones lógicas (adición, contraste, secuencia, semejanza-diferencia y causa) y jerárquicas (ideas principales) en textos orales en inglés.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C1-CAP3-D6P', 'Expresa sus ideas y emociones en torno a un tema con coherencia, cohesión y fluidez de acuerdo con su nivel, organizándolas para establecer relaciones lógicas (adición, contraste, secuencia, semejanza-diferencia y causa) y ampliando la información de forma pertinente con vocabulario apropiado.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C1-CAP4-D6P', 'Emplea gestos y movimientos para enfatizar lo que dice usando pronunciación, entonación y volumen adecuados; se apoya en material concreto y visual.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C1-CAP5-D6P', 'Participa en diversas situaciones comunicativas alternando los roles de hablante y oyente, para preguntar, responder, explicar, así como hacer comentarios relevantes en inglés con vocabulario de uso frecuente y pertinente; recurre a modos de cortesía según el contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C1-CAP6'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C1-CAP6-D6P', 'Opina en inglés como hablante y oyente sobre el contenido y el propósito comunicativo del texto oral, y sobre las intenciones de los interlocutores a partir de su experiencia y el contexto en el que se desenvuelve.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C2-CAP1-D6P', 'Identifica información explícita, relevante y complementaria distinguiéndola de otra cercana y semejante en diversos tipos de textos escritos en inglés con vocabulario de uso frecuente y pertinente.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C2-CAP2-D6P', 'Deduce relaciones lógicas (adición, contraste, secuencia, semejanza-diferencia, causa-efecto) y jerárquicas (ideas principales y complementarias) en textos escritos en inglés. Señala características de personas, animales, objetos, lugares, así como el significado de palabras, frases y expresiones en contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C2-CAP3-D6P', 'Opina en inglés de manera oral o escrita sobre el contenido y propósito comunicativo de los textos escritos en inglés, a partir de su experiencia y contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C3-CAP1-D6P', 'Adecúa el texto que escribe en inglés a la situación comunicativa considerando el tipo textual, algunas características del género discursivo, el formato, el soporte y el propósito.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C3-CAP2-D6P', 'Produce textos escritos en inglés en torno a un tema con coherencia, cohesión y fluidez de acuerdo con su nivel, organizándolas para establecer relaciones lógicas (adición, contraste, secuencia, semejanza-diferencia y causa) y ampliando información de forma pertinente con vocabulario apropiado.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C3-CAP3-D6P', 'Emplea convenciones del lenguaje escrito como recursos ortográficos y gramaticales de mediana complejidad que le dan claridad y sentido al texto. Ejemplo: modal verb can - yes / No questions and answers; coordinating conjunctions - and, but; verb to be; present simple; action verbs; wh-questions - what, how, where, what color, what number; demonstrative pronouns - this, that, these, those; possessive pronouns - my, your, his, her; possessive adjectives; personal pronouns - I, you, it, she, he, we, they; adjectives - young, old, small, big, tall, short.'),
((SELECT id FROM capacidades WHERE codigo = 'ING-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ING-C3-CAP4-D6P', 'Revisa su texto en inglés para mejorarlo; considera aspectos gramaticales y ortográficos básicos vinculados con el lenguaje escrito para dar sentido al texto.');
