-- =====================================================
-- MIGRATION: Add Primaria Desempeños - Phase 1 Part 3
-- Areas: Ciencia y Tecnología (CYT) - Grados 1° y 2°
-- =====================================================

-- CIENCIA Y TECNOLOGÍA (CYT) - 1° Primaria (11 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'CYT-C1-CAP1-D1P', 'Hace preguntas acerca de hechos, fenómenos u objetos naturales y tecnológicos que explora y observa en su entorno. Propone posibles respuestas basándose en sus experiencias.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'CYT-C1-CAP2-D1P', 'Propone acciones que le permiten responder a la pregunta y las ordena secuencialmente. Selecciona los materiales, instrumentos y herramientas necesarios para explorar, observar y recoger datos.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'CYT-C1-CAP3-D1P', 'Obtiene y registra datos, a partir de las acciones que realizó para responder a la pregunta. Utiliza algunos organizadores de información o representa los datos mediante dibujos o sus primeras formas de escritura.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'CYT-C1-CAP4-D1P', 'Compara y establece si hay diferencia entre su respuesta inicial y los datos o información obtenida en su observación o experimentación. Elabora sus conclusiones.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'CYT-C1-CAP5-D1P', 'Comunica las respuestas que dio a la pregunta, lo que aprendió, así como sus logros y dificultades, mediante diversas formas de expresión: gráficas, orales o a través de su nivel de escritura.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'CYT-C2-CAP1-D1P', 'Describe las características y necesidades de los seres vivos. Ejemplo: El estudiante describe qué necesitan los seres vivos para vivir: alimentos, oxígeno, etc.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'CYT-C2-CAP2-D1P', 'Relaciona las actividades cotidianas con el uso de la energía. Ejemplo: El estudiante relaciona el uso de gas en su cocina con la cocción de sus alimentos, o el uso de pilas con el funcionamiento de sus juguetes.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'CYT-C3-CAP1-D1P', 'Selecciona un problema tecnológico de su entorno. Explica su alternativa de solución con base en conocimientos previos o prácticas locales; considera los requerimientos que debe cumplir y los recursos disponibles para construirla.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'CYT-C3-CAP2-D1P', 'Representa su alternativa de solución tecnológica con dibujos y textos. Describe lo que hará para construirla.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'CYT-C3-CAP3-D1P', 'Construye su alternativa de solución tecnológica manipulando materiales, instrumentos y herramientas; cumple las normas de seguridad y considera medidas de ecoeficiencia. Usa unidades de medida no convencionales. Realiza ensayos hasta que funcione.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'CYT-C3-CAP4-D1P', 'Realiza pruebas para verificar si la solución tecnológica cumple con los requerimientos establecidos. Explica cómo construyó su solución tecnológica y las dificultades que tuvo.');

-- CIENCIA Y TECNOLOGÍA (CYT) - 2° Primaria (11 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'CYT-C1-CAP1-D2P', 'Hace preguntas acerca de hechos, fenómenos u objetos naturales y tecnológicos que explora. Elabora una posible respuesta con base en sus experiencias.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'CYT-C1-CAP2-D2P', 'Propone acciones que le permiten responder a la pregunta. Busca información, selecciona los materiales e instrumentos que necesitará para explorar y observar objetos, hechos o fenómenos, recoger datos y registrarlos.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'CYT-C1-CAP3-D2P', 'Obtiene y registra datos a partir de las acciones que realizó para responder a la pregunta. Utiliza algunos organizadores de información y representa los datos en dibujos o gráficos.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'CYT-C1-CAP4-D2P', 'Compara su respuesta inicial con los datos o la información obtenida en su observación o experimentación. Elabora sus conclusiones.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'CYT-C1-CAP5-D2P', 'Comunica las respuestas que dio a la pregunta, lo que aprendió, así como sus logros y dificultades, mediante diversas formas de expresión: gráficas, orales o a través de la escritura.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'CYT-C2-CAP1-D2P', 'Describe las características de los seres vivos y los objetos inertes. Compara las semejanzas y diferencias entre ellos. Ejemplo: El estudiante describe que los seres vivos crecen, se reproducen y mueren, mientras que los objetos inertes no.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'CYT-C2-CAP2-D2P', 'Relaciona el comportamiento de los seres vivos con los cambios de clima. Ejemplo: El estudiante da razones de por qué cuando hace frío tenemos que abrigarnos más y cuando hace calor buscamos lugares frescos.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'CYT-C3-CAP1-D2P', 'Determina el problema tecnológico y las causas que lo generan. Propone alternativas de solución con base en conocimientos previos o prácticas locales; considera los requerimientos que debe cumplir y los recursos disponibles para construirla.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'CYT-C3-CAP2-D2P', 'Representa su alternativa de solución tecnológica con dibujos y textos; describe sus partes, la secuencia de pasos para su elaboración y selecciona herramientas, instrumentos y materiales según sus propiedades.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'CYT-C3-CAP3-D2P', 'Construye su alternativa de solución tecnológica manipulando materiales, instrumentos y herramientas según su utilidad; cumple las normas de seguridad y considera medidas de ecoeficiencia. Usa unidades de medida convencionales. Realiza cambios o ajustes para cumplir los requerimientos o mejorar el funcionamiento de su alternativa de solución tecnológica.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'CYT-C3-CAP4-D2P', 'Realiza pruebas para verificar el funcionamiento de su alternativa de solución tecnológica con los requerimientos establecidos. Describe cómo la construyó, su uso, beneficios y los conocimientos previos o prácticas locales aplicadas. Comenta las dificultades que tuvo.');
