-- =====================================================
-- MIGRATION: Add Primaria Desempeños - Phase 1 (Core Areas)
-- Areas: Matemática (MAT), Comunicación (COM)
-- Grados: 1° a 6° Primaria
-- =====================================================

-- MATEMÁTICA - Completar grados faltantes (4°, 5°, 6°)
-- Ya existen: 1° (5), 2° (4), 3° (4)
-- Faltantes: 4° (4), 5° (4), 6° (4) = 12 desempeños

-- 4° Primaria - Matemática
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'MAT-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'MAT-C1-CAP1-D4P', 'Traduce cantidades hasta seis cifras y magnitudes (longitud, masa, tiempo, temperatura) a expresiones numéricas con números naturales, fracciones usuales y decimales hasta el centésimo, estableciendo relaciones entre representaciones.'),
((SELECT id FROM capacidades WHERE codigo = 'MAT-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'MAT-C1-CAP2-D4P', 'Comunica su comprensión de los números naturales hasta seis cifras, fracciones usuales y decimales hasta el centésimo, sus equivalencias y propiedades, usando lenguaje numérico y diversas representaciones.'),
((SELECT id FROM capacidades WHERE codigo = 'MAT-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'MAT-C1-CAP3-D4P', 'Usa estrategias y procedimientos de estimación y cálculo para operar con números naturales hasta seis cifras, fracciones usuales y decimales hasta el centésimo, seleccionando la estrategia más pertinente.'),
((SELECT id FROM capacidades WHERE codigo = 'MAT-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'MAT-C1-CAP4-D4P', 'Argumenta afirmaciones sobre las relaciones numéricas y las operaciones con números naturales, fracciones y decimales, explicando con ejemplos y propiedades matemáticas.');

-- 5° Primaria - Matemática
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'MAT-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'MAT-C1-CAP1-D5P', 'Traduce cantidades de hasta seis cifras y magnitudes a expresiones numéricas con números naturales, fracciones, decimales hasta el milésimo y porcentajes usuales, estableciendo relaciones entre diferentes representaciones.'),
((SELECT id FROM capacidades WHERE codigo = 'MAT-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'MAT-C1-CAP2-D5P', 'Comunica su comprensión de los números naturales, fracciones, decimales hasta el milésimo y porcentajes usuales, sus equivalencias, orden y propiedades, usando lenguaje numérico y diversas representaciones.'),
((SELECT id FROM capacidades WHERE codigo = 'MAT-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'MAT-C1-CAP3-D5P', 'Usa estrategias y procedimientos de estimación y cálculo para operar con números naturales, fracciones, decimales y porcentajes, seleccionando y adaptando estrategias según la situación.'),
((SELECT id FROM capacidades WHERE codigo = 'MAT-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'MAT-C1-CAP4-D5P', 'Argumenta afirmaciones sobre las relaciones numéricas y las operaciones, explicando con ejemplos, contraejemplos y propiedades matemáticas.');

-- 6° Primaria - Matemática
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'MAT-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'MAT-C1-CAP1-D6P', 'Traduce cantidades y magnitudes a expresiones numéricas con números naturales, fracciones, decimales, porcentajes y números enteros, estableciendo relaciones entre diferentes representaciones y reconociendo la utilidad de cada una.'),
((SELECT id FROM capacidades WHERE codigo = 'MAT-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'MAT-C1-CAP2-D6P', 'Comunica su comprensión de los números naturales, fracciones, decimales, porcentajes y números enteros, sus equivalencias, orden, propiedades y operaciones, usando lenguaje numérico y diversas representaciones con precisión.'),
((SELECT id FROM capacidades WHERE codigo = 'MAT-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'MAT-C1-CAP3-D6P', 'Usa estrategias y procedimientos de estimación y cálculo para operar con números naturales, fracciones, decimales, porcentajes y números enteros, combinando estrategias de manera flexible y eficiente.'),
((SELECT id FROM capacidades WHERE codigo = 'MAT-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'MAT-C1-CAP4-D6P', 'Argumenta afirmaciones sobre las relaciones numéricas y las operaciones, justificando y validando sus conclusiones con ejemplos, contraejemplos y propiedades matemáticas.');

-- COMUNICACIÓN - Completar todos los grados
-- Ya existen: 1° (7), 2° (2), 3° (2)
-- Necesitamos agregar más desempeños para 1°, 2°, 3° y todos para 4°, 5°, 6°

-- 1° Primaria - Comunicación (agregar faltantes - ya tiene 7)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'COM-C2-CAP1-D1P-2', 'Obtiene información explícita que se encuentra en lugares evidentes del texto (inicio, final), con vocabulario sencillo, en diversos tipos de textos escritos.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'COM-C2-CAP2-D1P-2', 'Infiere información anticipando el contenido del texto a partir de algunos indicios (título, ilustraciones, palabras conocidas) y deduciendo características de personajes, animales, objetos y lugares.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'COM-C2-CAP3-D1P-2', 'Reflexiona y evalúa los textos que lee, opinando acerca de personas, personajes y hechos, y explicando el propósito de los textos que lee con ayuda del docente.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'COM-C3-CAP1-D1P-2', 'Adecúa el texto a la situación comunicativa considerando el propósito comunicativo y el destinatario, recurriendo a su experiencia para escribir.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'COM-C3-CAP2-D1P-2', 'Organiza y desarrolla las ideas de forma coherente y cohesionada, ordenando las ideas en torno a un tema y utilizando algunos conectores de adición y secuencia.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'COM-C3-CAP3-D1P-2', 'Utiliza convenciones del lenguaje escrito de forma pertinente, usando recursos gramaticales y ortográficos básicos (mayúsculas, punto final) que contribuyen al sentido de su texto.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'COM-C3-CAP4-D1P-2', 'Reflexiona y evalúa la forma, el contenido y contexto del texto escrito, revisando si se mantiene en el tema y si el contenido se adecúa al destinatario con ayuda del docente.');

-- 2° Primaria - Comunicación (agregar faltantes - ya tiene 2)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C1-CAP1-D2P-2', 'Obtiene información explícita y relevante que se encuentra en distintas partes del texto oral, distinguiéndola de otra información semejante en diversos tipos de textos orales.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C1-CAP2-D2P-2', 'Infiere información deduciendo características de personas, personajes, animales, objetos, hechos y lugares, o el significado de palabras y expresiones en contexto a partir de información explícita del texto oral.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C1-CAP3-D2P-2', 'Adecúa su texto oral a la situación comunicativa y a sus interlocutores considerando el propósito comunicativo, utilizando recursos no verbales (gestos y movimientos corporales) y recurriendo a su experiencia.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C1-CAP4-D2P-2', 'Expresa oralmente ideas y emociones en torno a un tema, de forma coherente y cohesionada, ordenando las ideas y utilizando conectores de adición y secuencia.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C1-CAP5-D2P-2', 'Interactúa estratégicamente con distintos interlocutores, participando en diversos intercambios orales alternando los roles de hablante y oyente, y utilizando normas de cortesía sencillas.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP6'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C1-CAP6-D2P-2', 'Reflexiona y evalúa la forma, el contenido y contexto del texto oral, opinando sobre personas, personajes y hechos de los textos orales que escucha.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C2-CAP1-D2P-2', 'Obtiene información explícita y relevante ubicada en distintas partes del texto, distinguiéndola de otra información semejante en diversos tipos de textos escritos con vocabulario variado.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C2-CAP2-D2P-2', 'Infiere información anticipando el contenido del texto, deduciendo características de personajes, animales, objetos y lugares, así como el significado de palabras en contexto y relaciones lógicas de causa-efecto.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C2-CAP3-D2P-2', 'Reflexiona y evalúa los textos escritos, opinando acerca de personas, personajes y hechos, y explicando el propósito y la enseñanza de los textos que lee.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C3-CAP1-D2P-2', 'Adecúa el texto a la situación comunicativa considerando el propósito comunicativo, el tipo textual y algunas características del género discursivo, así como el formato y el soporte.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C3-CAP2-D2P-2', 'Organiza y desarrolla las ideas de forma coherente y cohesionada, estableciendo relaciones entre las ideas a través del uso adecuado de algunos conectores y referentes.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C3-CAP3-D2P-2', 'Utiliza convenciones del lenguaje escrito de forma pertinente, usando recursos gramaticales y ortográficos (mayúsculas, punto final, coma enumerativa) para dar claridad y sentido a su texto.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'COM-C3-CAP4-D2P-2', 'Reflexiona y evalúa de manera permanente el texto que escribe, revisando si se adecúa al destinatario, propósito, tema, registro y tipo textual, así como la coherencia entre las ideas.');

-- 3° Primaria - Comunicación (agregar faltantes - ya tiene 2)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C1-CAP1-D3P-2', 'Obtiene información explícita y relevante ubicada en distintas partes del texto oral, distinguiéndola de otra información cercana y semejante en diversos tipos de textos orales con vocabulario variado.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C1-CAP2-D3P-2', 'Infiere información deduciendo características implícitas de personas, personajes, animales, objetos, hechos y lugares, o el significado de palabras y expresiones según el contexto, así como relaciones lógicas entre las ideas del texto oral.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C1-CAP3-D3P-2', 'Adecúa su texto oral a la situación comunicativa, de acuerdo al propósito comunicativo, así como a las características del género discursivo, manteniendo el registro formal e informal según sus interlocutores.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C1-CAP4-D3P-2', 'Expresa oralmente ideas y emociones en torno a un tema, de forma coherente y cohesionada, ordenando y jerarquizando las ideas, y utilizando conectores y algunos referentes.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C1-CAP5-D3P-2', 'Interactúa estratégicamente con distintos interlocutores, participando en diversos intercambios orales, formulando preguntas, explicando sus respuestas y haciendo comentarios relevantes al tema.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C1-CAP6'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C1-CAP6-D3P-2', 'Reflexiona y evalúa la forma, el contenido y contexto del texto oral, opinando sobre las ideas, el propósito y la intención del interlocutor, y evaluando la eficacia de los recursos verbales y no verbales utilizados.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C2-CAP1-D3P-2', 'Obtiene información explícita y relevante ubicada en distintas partes del texto escrito, distinguiéndola de otra información cercana y semejante, en diversos tipos de textos con vocabulario variado.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C2-CAP2-D3P-2', 'Infiere información deduciendo características implícitas de personajes, animales, objetos y lugares, así como el significado de palabras en contexto y relaciones lógicas de causa-efecto, semejanza-diferencia y enseñanza y propósito.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C2-CAP3-D3P-2', 'Reflexiona y evalúa los textos escritos, opinando acerca del contenido y explicando el sentido de algunos recursos textuales (ilustraciones, tamaño de letra), a partir de su experiencia y contexto.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C3-CAP1-D3P-2', 'Adecúa el texto a la situación comunicativa considerando el propósito comunicativo, el tipo textual y algunas características del género discursivo, así como el formato y el soporte, manteniendo el registro formal e informal.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C3-CAP2-D3P-2', 'Organiza y desarrolla las ideas de forma coherente y cohesionada, estableciendo relaciones lógicas entre ellas a través del uso adecuado de algunos conectores y referentes, y utilizando recursos gramaticales y ortográficos.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C3-CAP3-D3P-2', 'Utiliza convenciones del lenguaje escrito de forma pertinente, usando recursos gramaticales y ortográficos (mayúsculas, punto seguido, coma enumerativa, signos de interrogación y exclamación) para dar claridad y sentido a su texto.'),
((SELECT id FROM capacidades WHERE codigo = 'COM-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'COM-C3-CAP4-D3P-2', 'Reflexiona y evalúa de manera permanente el texto que escribe, revisando si se adecúa a la situación comunicativa, si las ideas son coherentes entre sí, y si el uso de conectores y referentes asegura la cohesión del texto.');
