-- =====================================================
-- MIGRATION: Add Primaria Desempeños - Phase 2 Complementary Areas
-- Areas: Arte y Cultura (ART), Educación Física (EF), Educación Religiosa (ER)
-- Total: ~144 desempeños
-- =====================================================

-- ARTE Y CULTURA (ART) - 1° Primaria (9 desempeños: 3 caps × 3 competencias)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
-- Competencia 1: Aprecia de manera crítica manifestaciones artístico-culturales
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ART-C1-CAP1-D1P', 'Usa los sentidos para identificar, con la ayuda del docente, los elementos visuales, táctiles, sonoros y kinestésicos que hay en la naturaleza, el entorno y diversas manifestaciones artísticas de su contexto local.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ART-C1-CAP2-D1P', 'Menciona y describe las experiencias que tiene con manifestaciones artísticas en su entorno familiar y en su comunidad. Ejemplo: El estudiante conversa sobre situaciones, eventos u ocasiones donde ha tenido oportunidad de vivir o experimentar la música (cuando su mamá le canta o cuando oye música para bailar en su casa, en fiestas o en celebraciones de su barrio).'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ART-C1-CAP3-D1P', 'Explica sus ideas y expresa sus emociones y sentimientos cuando entra en contacto con la naturaleza o manifestaciones artístico-culturales de su entorno.'),
-- Competencia 2: Crea proyectos desde los lenguajes artísticos
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ART-C2-CAP1-D1P', 'Experimenta con los medios, los materiales y las técnicas artísticas para crear efectos visuales, sonoros, vocales o kinestésicos en respuesta a estímulos del docente o con base en sus propias exploraciones. Ejemplo: El estudiante realiza movimientos según los ritmos que toca el profesor en un tambor, y altera o exagera sus movimientos cuando hay cambios de ritmo.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ART-C2-CAP2-D1P', 'Explora ideas libremente a partir de su imaginación, sus experiencias u observaciones, y experimenta maneras en que los elementos del arte (movimientos, acciones, formas, colores o sonidos) pueden usarse o ser repetidos para comunicar una idea. Ejemplo: El estudiante realiza un trabajo de técnica mixta usando papeles y materiales de collage que el docente ha dispuesto sobre una mesa. Elige pedazos de papel de diferentes formas, colores y tamaños y los pega haciendo su propia composición.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Primaria'), 'ART-C2-CAP3-D1P', 'Presenta sus trabajos y creaciones y responde a preguntas sencillas sobre ellos; asimismo, describe las características de sus propios trabajos y los de sus compañeros.');

-- ARTE Y CULTURA (ART) - 2° Primaria (9 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ART-C1-CAP1-D2P', 'Usa los sentidos para identificar, con la ayuda del docente, los elementos visuales, táctiles, sonoros y kinestésicos que hay en la naturaleza, el entorno y diversas manifestaciones artísticas de su contexto local.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ART-C1-CAP2-D2P', 'Menciona y describe las experiencias que tiene con manifestaciones artísticas en su entorno familiar y en su comunidad. Identifica cómo el arte cumple diversas funciones (socializar, entretener, contar historias, celebrar) en su comunidad.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ART-C1-CAP3-D2P', 'Explica sus ideas y expresa sus emociones y sentimientos cuando entra en contacto con la naturaleza o manifestaciones artístico-culturales de su entorno.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ART-C2-CAP1-D2P', 'Experimenta con los medios, los materiales y las técnicas artísticas para crear efectos visuales, sonoros, vocales o kinestésicos en respuesta a estímulos del docente o con base en sus propias exploraciones.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ART-C2-CAP2-D2P', 'Explora ideas libremente a partir de su imaginación, sus experiencias u observaciones, y experimenta maneras en que los elementos del arte pueden usarse o ser repetidos para comunicar una idea.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Primaria'), 'ART-C2-CAP3-D2P', 'Presenta sus trabajos y creaciones y responde a preguntas sencillas sobre ellos; asimismo, describe las características de sus propios trabajos y los de sus compañeros.');

-- ARTE Y CULTURA (ART) - 3° Primaria (9 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ART-C1-CAP1-D3P', 'Identifica y describe los elementos básicos del arte que encuentra en su entorno y en manifestaciones artístico-culturales diversas. Reconoce que los elementos pueden transmitir múltiples sensaciones.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ART-C1-CAP2-D3P', 'Especula sobre los procesos que el artista ha seguido para crear su obra e identifica los distintos usos y propósitos de manifestaciones artístico-culturales de su comunidad (ritual, recreativo, comercial, decorativo, utilitario, etc.).'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ART-C1-CAP3-D3P', 'Comenta sobre los posibles significados de una obra de arte, con base en lo observado y lo investigado acerca del autor, y emite una opinión personal sobre ella.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ART-C2-CAP1-D3P', 'Improvisa y experimenta maneras de usar los elementos del arte y reconoce los efectos que puede lograr combinando diversos medios, materiales, herramientas y técnicas para comunicar ideas. Ejemplo: El estudiante realiza mezclas de color con témperas, para crear diferentes tonos de color que se parezcan más a su color de piel al hacer su autoretrato.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ART-C2-CAP2-D3P', 'Genera ideas a partir de intereses, de experiencias personales, de la observación de su entorno natural y social o de estímulos externos. Empieza a seleccionar y organizar elementos (movimientos, acciones o efectos visuales o sonoros) para presentar una idea de una manera en particular.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Primaria'), 'ART-C2-CAP3-D3P', 'Presenta sus trabajos y creaciones en forma individual y grupal, y describe de manera sencilla cómo los ha creado y organizado.');

-- ARTE Y CULTURA (ART) - 4° Primaria (9 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ART-C1-CAP1-D4P', 'Identifica y describe los contextos de diversas manifestaciones artístico-culturales e identifica cómo el arte cumple diversas funciones (socializar, entretener, contar historias, celebrar) y ayuda a conocer las creencias, los valores o las actitudes de un artista o una sociedad. Ejemplo: El estudiante explica qué representa la danza Chuño Saruy para las comunidades que la realizan, por qué la hacen y de qué lugar proviene.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ART-C1-CAP2-D4P', 'Identifica y describe los elementos básicos del arte que encuentra en su entorno y en manifestaciones artístico-culturales diversas. Reconoce que los elementos pueden transmitir múltiples sensaciones.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ART-C1-CAP3-D4P', 'Comenta sobre la manera en que los elementos, los procesos, los medios y las técnicas usadas comunican ideas, y genera hipótesis sobre el significado y la intención del artista.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ART-C2-CAP1-D4P', 'Combina y busca alternativas para usar elementos de los lenguajes artísticos, medios, materiales, herramientas, técnicas, recursos tecnológicos a su alcance, así como prácticas tradicionales de su comunidad, para expresar de diferentes maneras sus ideas.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ART-C2-CAP2-D4P', 'Desarrolla sus ideas a partir de observaciones, experiencias y el trabajo artístico de otros, y selecciona elementos y materiales para componer una imagen de acuerdo a sus intenciones.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '4° Primaria'), 'ART-C2-CAP3-D4P', 'Planifica maneras de presentar sus trabajos para comunicar sus ideas efectivamente, donde asume un rol específico. Explica las razones por las que ha seleccionado medios, materiales, herramientas y técnicas específicas en sus trabajos y evalúa con criterios dados si logró su propósito.');

-- ARTE Y CULTURA (ART) - 5° Primaria (9 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ART-C1-CAP1-D5P', 'Describe y analiza los elementos del arte que identifica en el entorno y en manifestaciones artístico-culturales, e identifica los medios utilizados. Relaciona elementos con ideas, mensajes y sentimientos.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ART-C1-CAP2-D5P', 'Identifica y describe los contextos de diversas manifestaciones artístico-culturales e identifica cómo el arte cumple diversas funciones (socializar, entretener, contar historias, celebrar) y ayuda a conocer las creencias, los valores o las actitudes de un artista o una sociedad.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ART-C1-CAP3-D5P', 'Genera hipótesis sobre el significado y las diversas intenciones que puede tener una manifestación artístico-cultural, y discute sobre ello con sus compañeros. Evalúa la efectividad del uso de las técnicas utilizadas.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ART-C2-CAP1-D5P', 'Combina y busca alternativas para usar elementos de los lenguajes artísticos, medios, materiales, herramientas, técnicas, recursos tecnológicos a su alcance, así como prácticas tradicionales de su comunidad, para expresar de diferentes maneras sus ideas.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ART-C2-CAP2-D5P', 'Desarrolla sus ideas a partir de observaciones, experiencias y el trabajo artístico de otros, y selecciona elementos y materiales para componer una imagen de acuerdo a sus intenciones.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '5° Primaria'), 'ART-C2-CAP3-D5P', 'Planifica maneras de presentar sus trabajos para comunicar sus ideas efectivamente, donde asume un rol específico. Explica las razones por las que ha seleccionado medios, materiales, herramientas y técnicas específicas en sus trabajos y evalúa con criterios dados si logró su propósito.');

-- ARTE Y CULTURA (ART) - 6° Primaria (9 desempeños)
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ART-C1-CAP1-D6P', 'Describe y analiza los elementos del arte que identifica en el entorno y en manifestaciones artístico-culturales, e identifica los medios utilizados. Relaciona elementos con ideas, mensajes y sentimientos. Ejemplo: El estudiante observa una danza de su localidad, describe los movimientos y elementos que la componen, y explica qué es lo que le hace sentir.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ART-C1-CAP2-D6P', 'Investiga los contextos donde se originan manifestaciones artístico-culturales tradicionales y contemporáneas, e identifica cómo los cambios, las tradiciones, las creencias y valores revelan la manera en que una determinada persona o sociedad ha vivido.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ART-C1-CAP3-D6P', 'Genera hipótesis sobre el significado y las diversas intenciones que puede tener una manifestación artístico-cultural, y discute sobre ello con sus compañeros. Evalúa la efectividad del uso de las técnicas utilizadas en relación a las intenciones específicas.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ART-C2-CAP1-D6P', 'Combina y busca alternativas para usar elementos de los lenguajes artísticos, medios, materiales, herramientas, técnicas, recursos tecnológicos a su alcance, así como prácticas tradicionales de su comunidad, para expresar de diferentes maneras sus ideas.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ART-C2-CAP2-D6P', 'Desarrolla sus ideas a partir de observaciones, experiencias y el trabajo artístico de otros, y selecciona elementos y materiales para componer una imagen de acuerdo a sus intenciones. Registra sus ideas y las influencias de sus creaciones y las presenta de diversas maneras.'),
((SELECT id FROM capacidades WHERE codigo = 'ART-C2-CAP3'), (SELECT id FROM grados WHERE nombre = '6° Primaria'), 'ART-C2-CAP3-D6P', 'Planifica maneras de presentar sus trabajos para comunicar sus ideas efectivamente, donde asume un rol específico. Explica las razones por las que ha seleccionado medios, materiales, herramientas y técnicas específicas en sus trabajos, y evalúa con criterios propios y dados si logró su propósito.');
