-- Migration: Expand Ciencia y Tecnología with Capacidades and Desempeños
-- Phase 1: Complete CYT area with CNEB-compliant content
-- Date: 2026-02-17

-- ============================================================================
-- CAPACIDADES for Ciencia y Tecnología
-- ============================================================================

-- Competencia CYT-C1: Indaga mediante métodos científicos para construir conocimientos
INSERT INTO capacidades (competencia_id, codigo, nombre, descripcion) VALUES
((SELECT id FROM competencias WHERE codigo = 'CYT-C1'), 'CYT-C1-CAP1', 'Problematiza situaciones para hacer indagación', 'El estudiante plantea preguntas sobre hechos y fenómenos naturales, interpreta situaciones y formula hipótesis.'),
((SELECT id FROM competencias WHERE codigo = 'CYT-C1'), 'CYT-C1-CAP2', 'Diseña estrategias para hacer indagación', 'El estudiante propone actividades que permitan construir un procedimiento, seleccionar materiales, instrumentos e información para comprobar o refutar la hipótesis.'),
((SELECT id FROM competencias WHERE codigo = 'CYT-C1'), 'CYT-C1-CAP3', 'Genera y registra datos e información', 'El estudiante obtiene, organiza y registra datos fiables en función de las variables, utilizando instrumentos y diversas técnicas.'),
((SELECT id FROM competencias WHERE codigo = 'CYT-C1'), 'CYT-C1-CAP4', 'Analiza datos e información', 'El estudiante interpreta los datos obtenidos en la indagación, los contrasta con las hipótesis e información relacionada al problema, y elabora conclusiones.'),
((SELECT id FROM competencias WHERE codigo = 'CYT-C1'), 'CYT-C1-CAP5', 'Evalúa y comunica el proceso y resultados de su indagación', 'El estudiante identifica y da a conocer las dificultades técnicas y los conocimientos logrados para cuestionar el grado de satisfacción que la respuesta da a la pregunta de indagación.');

-- Competencia CYT-C2: Explica el mundo físico basándose en conocimientos sobre los seres vivos, materia y energía, biodiversidad, Tierra y universo
INSERT INTO capacidades (competencia_id, codigo, nombre, descripcion) VALUES
((SELECT id FROM competencias WHERE codigo = 'CYT-C2'), 'CYT-C2-CAP1', 'Comprende y usa conocimientos sobre los seres vivos, materia y energía, biodiversidad, Tierra y universo', 'El estudiante establece relaciones entre varios conceptos y los transfiere a nuevas situaciones. Esto le permite construir representaciones del mundo natural y artificial.'),
((SELECT id FROM competencias WHERE codigo = 'CYT-C2'), 'CYT-C2-CAP2', 'Evalúa las implicancias del saber y del quehacer científico y tecnológico', 'El estudiante establece las relaciones entre la ciencia, la tecnología y la sociedad, y reflexiona sobre su impacto en el ambiente y en la forma de vivir.');

-- Competencia CYT-C3: Diseña y construye soluciones tecnológicas para resolver problemas de su entorno
INSERT INTO capacidades (competencia_id, codigo, nombre, descripcion) VALUES
((SELECT id FROM competencias WHERE codigo = 'CYT-C3'), 'CYT-C3-CAP1', 'Determina una alternativa de solución tecnológica', 'El estudiante detecta un problema y propone alternativas de solución creativas basadas en conocimientos científico-tecnológicos y prácticas locales.'),
((SELECT id FROM competencias WHERE codigo = 'CYT-C3'), 'CYT-C3-CAP2', 'Diseña la alternativa de solución tecnológica', 'El estudiante establece las características de su alternativa de solución, selecciona los recursos necesarios, y elabora representaciones gráficas.'),
((SELECT id FROM competencias WHERE codigo = 'CYT-C3'), 'CYT-C3-CAP3', 'Implementa y valida la alternativa de solución tecnológica', 'El estudiante lleva a cabo el procedimiento para la implementación de su alternativa de solución y realiza pruebas para verificar su funcionamiento.'),
((SELECT id FROM competencias WHERE codigo = 'CYT-C3'), 'CYT-C3-CAP4', 'Evalúa y comunica el funcionamiento y los impactos de su alternativa de solución tecnológica', 'El estudiante determina qué tan bien la solución tecnológica logró responder a los requerimientos del problema, propone mejoras y comunica su funcionamiento.');

-- ============================================================================
-- DESEMPEÑOS for CYT-C1: Indaga mediante métodos científicos
-- ============================================================================

-- Capacidad: Problematiza situaciones para hacer indagación
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Secundaria'), 'CYT-C1-CAP1-D1', 'Formula preguntas acerca de las variables que influyen en un hecho, fenómeno u objeto natural o tecnológico, y selecciona aquella que puede ser indagada científicamente. Plantea hipótesis en las que establece relaciones de causalidad entre las variables.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Secundaria'), 'CYT-C1-CAP1-D2', 'Formula preguntas sobre el hecho, fenómeno u objeto natural o tecnológico que indaga para delimitar el problema. Observa el comportamiento de las variables. Plantea hipótesis que expresan la relación causa-efecto y determina las variables involucradas.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Secundaria'), 'CYT-C1-CAP1-D3', 'Formula preguntas, establece la relación del problema que va a investigar con un conjunto de conocimientos científicos, y delimita el problema. Determina las variables dependiente e independiente y las intervinientes en el proceso de indagación. Plantea hipótesis en las que establece relaciones de causalidad entre las variables.');

-- Capacidad: Diseña estrategias para hacer indagación
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Secundaria'), 'CYT-C1-CAP2-D1', 'Propone procedimientos para observar, manipular la variable independiente, medir la variable dependiente y controlar aspectos que modifican la experimentación. Selecciona herramientas, materiales e instrumentos para recoger datos cualitativos/cuantitativos. Prevé el tiempo y las medidas de seguridad personal y del lugar de trabajo.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Secundaria'), 'CYT-C1-CAP2-D2', 'Propone procedimientos para manipular la variable independiente, medir la variable dependiente y mantener constantes las intervinientes. Selecciona herramientas, materiales, equipos e instrumentos apropiados, y elige las unidades de medida que va a utilizar en cada variable. Propone medidas de seguridad.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Secundaria'), 'CYT-C1-CAP2-D3', 'Propone y fundamenta, sobre la base de los objetivos de su indagación e información científica, procedimientos que le permitan observar, manipular y medir las variables y el tiempo por emplear, las medidas de seguridad, y las herramientas, materiales e instrumentos de recojo de datos cualitativos/cuantitativos para confirmar o refutar la hipótesis.');

-- Capacidad: Genera y registra datos e información
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Secundaria'), 'CYT-C1-CAP3-D1', 'Obtiene datos cualitativos/cuantitativos a partir de la manipulación de la variable independiente y mediciones repetidas de la variable dependiente. Controla aspectos que modifican la experimentación. Organiza los datos y hace cálculos de la moda, proporcionalidad u otros, y los representa en gráficas.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Secundaria'), 'CYT-C1-CAP3-D2', 'Obtiene datos cualitativos/cuantitativos a partir de la manipulación de la variable independiente y de mediciones repetidas de la variable dependiente. Controla las variables intervinientes. Organiza los datos, hace cálculos de medidas de tendencia central, proporcionalidad u otros, obtiene el margen de error, y representa la incertidumbre con intervalos de confianza o estadísticos.');

-- Capacidad: Analiza datos e información
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '1° Secundaria'), 'CYT-C1-CAP4-D1', 'Compara los datos obtenidos (cualitativos y cuantitativos) para establecer relaciones de causalidad, correspondencia, equivalencia, pertenencia, similitud, diferencia u otros. Identifica regularidades o tendencias. Predice el comportamiento de las variables y contrasta los resultados con su hipótesis e información científica, para elaborar conclusiones.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '2° Secundaria'), 'CYT-C1-CAP4-D2', 'Compara los datos obtenidos (cualitativos y cuantitativos) para establecer relaciones de causalidad, correspondencia, equivalencia, pertenencia, similitud, diferencia u otros; contrasta los resultados con su hipótesis e información científica para confirmar o refutar su hipótesis, y elabora conclusiones.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP4'), (SELECT id FROM grados WHERE nombre = '3° Secundaria'), 'CYT-C1-CAP4-D3', 'Contrasta y complementa los datos o información de su indagación con el uso de fuentes de información. Elabora conclusiones que expliquen las relaciones investigadas. Evalúa la fiabilidad de los métodos y las interpretaciones de los resultados de su indagación.');

-- Capacidad: Evalúa y comunica el proceso y resultados de su indagación
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '1° Secundaria'), 'CYT-C1-CAP5-D1', 'Sustenta si sus conclusiones responden a la pregunta de indagación, y si los procedimientos, mediciones y ajustes realizados contribuyeron a demostrar su hipótesis. Comunica su indagación a través de medios virtuales o presenciales.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '2° Secundaria'), 'CYT-C1-CAP5-D2', 'Sustenta, sobre la base de conocimientos científicos, sus conclusiones, procedimientos y la reducción del error a través del uso del grupo de control, repetición de mediciones, cálculos y ajustes en la experimentación. Comunica su indagación a través de medios virtuales o presenciales.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C1-CAP5'), (SELECT id FROM grados WHERE nombre = '3° Secundaria'), 'CYT-C1-CAP5-D3', 'Sustenta, sobre la base de conocimientos científicos, sus conclusiones, los procedimientos y la reducción del error a través del uso del grupo de control, la repetición de mediciones, los cálculos y los ajustes realizados en la obtención de resultados válidos y fiables para demostrar la hipótesis y lograr el objetivo. Comunica su indagación a través de medios virtuales o presenciales.');

-- ============================================================================
-- DESEMPEÑOS for CYT-C2: Explica el mundo físico
-- ============================================================================

-- Capacidad: Comprende y usa conocimientos sobre los seres vivos, materia y energía, biodiversidad, Tierra y universo
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Secundaria'), 'CYT-C2-CAP1-D1', 'Explica, sobre la base de evidencias con respaldo científico, las relaciones cualitativas y las cuantificables que establece entre: el campo eléctrico con la estructura del átomo, la energía con el trabajo o el movimiento, las funciones de la célula con sus requerimientos de energía y materia, la selección natural o artificial con el origen y evolución de especies, los flujos de materia y energía en la Tierra o los fenómenos meteorológicos con el funcionamiento de la biosfera.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Secundaria'), 'CYT-C2-CAP1-D2', 'Explica, sobre la base de evidencias con respaldo científico, las relaciones cualitativas y las cuantificables entre: la estructura microscópica de un material y su reactividad con otros materiales o con campos y ondas; la información genética, las funciones de las células con las funciones de los sistemas (homeostasis); el origen de la Tierra, su composición, su evolución física, química y biológica con los registros fósiles.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP1'), (SELECT id FROM grados WHERE nombre = '3° Secundaria'), 'CYT-C2-CAP1-D3', 'Explica, sobre la base de evidencias con respaldo científico, las relaciones cualitativas y las cuantificables entre: el campo eléctrico con la estructura del átomo; la energía con el trabajo o el movimiento; las funciones de la célula con sus requerimientos de energía y materia; la selección natural o artificial con el origen y evolución de especies; los flujos de materia y energía en la Tierra con el ciclo biogeoquímico; la configuración de los gases con su comportamiento termodinámico.');

-- Capacidad: Evalúa las implicancias del saber y del quehacer científico y tecnológico
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Secundaria'), 'CYT-C2-CAP2-D1', 'Evalúa las implicancias éticas, sociales y ambientales de sistemas tecnológicos, y justifica su posición frente a ellos o a hechos paradigmáticos. Explica cómo el conocimiento científico se construye y modifica en respuesta a evidencias.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Secundaria'), 'CYT-C2-CAP2-D2', 'Fundamenta su posición ética, empleando evidencia científica, frente a eventos paradigmáticos y situaciones donde la ciencia y la tecnología son cuestionadas por su impacto en la sociedad y el ambiente.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C2-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Secundaria'), 'CYT-C2-CAP2-D3', 'Fundamenta su posición ética, empleando evidencia científica, frente a eventos paradigmáticos y situaciones donde la ciencia y la tecnología son cuestionadas por su impacto en la sociedad y el ambiente. Evalúa el rol de la ciencia y la tecnología en ese proceso.');

-- ============================================================================
-- DESEMPEÑOS for CYT-C3: Diseña y construye soluciones tecnológicas
-- ============================================================================

-- Capacidad: Determina una alternativa de solución tecnológica
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '1° Secundaria'), 'CYT-C3-CAP1-D1', 'Describe el problema tecnológico y las causas que lo generan. Explica su alternativa de solución tecnológica sobre la base de conocimientos científicos o prácticas locales. Da a conocer los requerimientos que debe cumplir esa alternativa de solución y los recursos disponibles para construirla.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP1'), (SELECT id FROM grados WHERE nombre = '2° Secundaria'), 'CYT-C3-CAP1-D2', 'Describe el problema tecnológico y las causas que lo generan. Explica su alternativa de solución tecnológica sobre la base de conocimientos científicos o prácticas locales. Da a conocer los requerimientos que debe cumplir esa alternativa de solución, los recursos disponibles para construirla, y sus beneficios directos e indirectos.');

-- Capacidad: Diseña la alternativa de solución tecnológica
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '1° Secundaria'), 'CYT-C3-CAP2-D1', 'Representa su alternativa de solución con dibujos estructurados. Describe sus partes o etapas, la secuencia de pasos, características de forma, estructura y función. Selecciona instrumentos, herramientas, recursos y materiales considerando su impacto ambiental y seguridad. Prevé posibles costos y tiempo de ejecución.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '2° Secundaria'), 'CYT-C3-CAP2-D2', 'Representa su alternativa de solución con dibujos estructurados a escala. Describe sus partes o etapas, la secuencia de pasos, características: dimensiones, forma, estructura, función. Selecciona instrumentos según propiedades físicas de los materiales, y herramientas según sus funciones básicas; verifica el funcionamiento de los instrumentos y la disponibilidad de los materiales. Prevé estrategias de seguridad, posibles costos y tiempo de ejecución.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP2'), (SELECT id FROM grados WHERE nombre = '3° Secundaria'), 'CYT-C3-CAP2-D3', 'Representa su alternativa de solución con dibujos estructurados a escala, con vistas y perspectivas, incluyendo aspectos de funcionamiento. Describe sus partes o etapas, la secuencia de pasos, características de forma, estructura, función y explica el procedimiento, los recursos para implementarla, así como las herramientas y materiales seleccionados. Justifica el margen de seguridad en el funcionamiento de su prototipo, las medidas de seguridad que debe aplicar y estima el costo de su proyecto.');

-- Capacidad: Implementa y valida la alternativa de solución tecnológica
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '1° Secundaria'), 'CYT-C3-CAP3-D1', 'Ejecuta la secuencia de pasos de su alternativa de solución manipulando materiales, herramientas e instrumentos, considerando normas de seguridad. Verifica el funcionamiento de cada parte o etapa de la solución tecnológica, detecta errores en los procedimientos o en la selección de materiales, y realiza ajustes o cambios según los requerimientos establecidos.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '2° Secundaria'), 'CYT-C3-CAP3-D2', 'Ejecuta la secuencia de pasos de su alternativa de solución manipulando materiales, herramientas e instrumentos considerando su grado de precisión y normas de seguridad. Verifica el funcionamiento de cada parte o etapa de la solución tecnológica; detecta errores en los procedimientos o en la selección de materiales, y realiza ajustes o cambios según los requerimientos establecidos.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP3'), (SELECT id FROM grados WHERE nombre = '3° Secundaria'), 'CYT-C3-CAP3-D3', 'Ejecuta la secuencia de pasos de su alternativa de solución manipulando materiales, herramientas e instrumentos considerando su grado de precisión. Verifica el funcionamiento de cada parte o etapa de la solución tecnológica; detecta errores en los procedimientos o en la selección de materiales, y realiza ajustes o cambios necesarios para cumplir los requerimientos establecidos.');

-- Capacidad: Evalúa y comunica el funcionamiento y los impactos de su alternativa de solución tecnológica
INSERT INTO desempenos (capacidad_id, grado_id, codigo, descripcion) VALUES
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '1° Secundaria'), 'CYT-C3-CAP4-D1', 'Comprueba el funcionamiento de su solución tecnológica según los requerimientos establecidos y propone mejoras. Explica su construcción, y los cambios o ajustes realizados sobre la base de conocimientos científicos o en prácticas locales, y determina el impacto ambiental durante su implementación y uso.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '2° Secundaria'), 'CYT-C3-CAP4-D2', 'Comprueba el funcionamiento de su solución tecnológica según los requerimientos establecidos y propone mejoras. Explica su construcción, y los cambios o ajustes realizados sobre la base de conocimientos científicos o en prácticas locales, y determina el impacto ambiental y social de su funcionamiento.'),
((SELECT id FROM capacidades WHERE codigo = 'CYT-C3-CAP4'), (SELECT id FROM grados WHERE nombre = '3° Secundaria'), 'CYT-C3-CAP4-D3', 'Comprueba el funcionamiento de su solución tecnológica según los requerimientos establecidos y propone mejoras para incrementar su eficiencia y reducir su impacto ambiental. Explica su construcción, y los cambios o ajustes realizados sobre la base de conocimientos científicos o en prácticas locales. Fundamenta su propuesta de mejora en fuentes de información confiables.');
